### ISSUE TITLE
想问一下这个程序是离线程序吗，还是在线的，如果在线的话是需要从网上获取什么呢？使用了之后这个软件一直从网上下载东西

### ISSUE THREAD

**Issue by chenanga** [BlueMatthew/WechatExporter#100]
![Snipaste_2022-05-31_09-14-15](https://user-images.githubusercontent.com/38496970/171074118-aebbade3-5dc3-4680-9335-96340c6a487a.png)

**Comment by BlueMatthew** [comment]
非微信内置的表情图片，备份中获取不到，需要直接下载。

**Comment by chenanga** [comment]
> 非微信编者的表情图片，直接备份中获取不到，需要下载。

好的，谢谢你！感谢作者大大的回复
