### ISSUE TITLE
可以调整一下转账的显示吗？

### ISSUE THREAD

**Issue by youbenliu** [BlueMatthew/WechatExporter#102]
可以调整一下转账的显示吗？现在导出来只能显示 [转账]   ，看不到金额或者备注说明，这个数据库里面有没有存储相关的信息能不能导出显示？
![image](https://user-images.githubusercontent.com/4945075/173172401-39b61c0e-478f-4242-9ede-63ce615eeaf8.png)

**Comment by BlueMatthew** [comment]
晚点我看一下数据

**Comment by BlueMatthew** [comment]
试一下1.9.5.10版本

**Comment by youbenliu** [comment]
> 
重新导出看了一下，已经可以显示了，谢谢大佬！！
