### ISSUE TITLE
解析iTunes文件失败

### ISSUE THREAD

**Issue by chloeclay** [BlueMatthew/WechatExporter#105]
mac os更新之后iTunes没有了，直接在finder里备份了手机。
但是试图用WechatExporter的时候总显示解析失败，日志显示LoginInfo2.dat not found。请问这个应该怎么办呀？

ios 15.2.1
macOS Monterey 12.4

**Comment by chloeclay** [comment]
补充：直接在finder里备份出来的文件名及文件路径和范例中的相同

**Comment by BlueMatthew** [comment]
你用的是最新的版本吗？最新的实现，LoginInfo2.dat 如果不存在，还会继续按微信账户目录去查找的，除非这几种方式都查不到。

MacOS 12.4我也测试过，应该是不影响的。

**Comment by BlueMatthew** [comment]
> [#86 (comment)](https://github.com/BlueMatthew/WechatExporter/issues/86#issuecomment-1086770454) 下载了这个可以解析了！希望帮到有同样问题的朋友们！ P.S. 感恩的心！！

最新的版本1.9.5.10反而不能导出吗？

**Comment by chloeclay** [comment]
> > [#86 (comment)](https://github.com/BlueMatthew/WechatExporter/issues/86#issuecomment-1086770454) 下载了这个可以解析了！希望帮到有同样问题的朋友们！ P.S. 感恩的心！！
> 
> 最新的版本1.9.5.10反而不能导出吗？

是的 我两个版本都试了一下，这个#86里的可以自动查到我的备份文件，反而是最新版的一直显示解析失败。

**Comment by BlueMatthew** [comment]
找到原因了，确实是macos编译的时候一个宏没有去掉，我晚上重新编译一个最新的版本，你到时候用最新的版本再试一下吧。

**Comment by BlueMatthew** [comment]
有空可以试试v1.9.5.11
