### ISSUE TITLE
群聊有人的头像图片无法加载

### ISSUE THREAD

**Issue by JakysonChen** [BlueMatthew/WechatExporter#113]
HTML中群聊有些人的头像显示为灰色

**Comment by BlueMatthew** [comment]
头像都是依赖于微信的缓存数据 如果微信转移过（譬如更换手机） 头像会被清除 而导致备份的时候找不到

**Comment by BlueMatthew** [comment]
群里面打开人员列表 头像就会重新下载 之后再次itunes备份就能导出来

**Comment by JakysonChen** [comment]
头像问题解决了，更新头像后用iTunes备份需要全量导出聊天记录才能刷新头像，在之前导出的聊天记录基础上用新的iTunes备份增量导出聊天记录头像依然无法刷新。还想请教下群昵称的问题，我发现群里有些人的昵称导出时显示的是很久以前的昵称，这也是跟微信的缓存有关系么？是否有办法解决？
