### ISSUE TITLE
关于增量导出的疑问

### ISSUE THREAD

**Issue by JakysonChen** [BlueMatthew/WechatExporter#114]
因为没有多余的小号可以测试，所以只能请教一下能否这样使用。比如我在8月1日使用iTunes进行了一次完整备份并用WechatExporter进行了完整导出，导出后将手机中的微信聊天记录全部删除，接着正常使用2个月微信。10月1日再次通过iTunes完整备份后，使用WechatExporter选择增量导出，并选择与8月1日相同的导出目录，软件提示检测到之前的导出记录并进行增量导出，此时就能成功将8月1日到10月1日之间的聊天记录合并到8月1日以及之前的聊天记录里，并在HTML中顺利正常显示是吧？

**Comment by BlueMatthew** [comment]
是这样的 不过为了以防万一的bug 建议你先把原来备份的目标目录拷贝一份出来 这样万一出现问题 原来的数据不致丢失或者损坏

**Comment by JakysonChen** [comment]
感谢解答~
