### ISSUE TITLE
希望支持导出A4大小的pdf文件，方便打印成册

### ISSUE THREAD

**Issue by Seifon** [BlueMatthew/WechatExporter#12]
有一款命令行导出工具，希望对你有所帮助。https://github.com/JabinGP/mdout

**Comment by BlueMatthew** [comment]
谢谢提供信息，后面我考虑一下导出pdf的格式。不过pdf貌似比较复杂（拍脑袋的感觉:) ），估计不能很快搞定。

**Comment by Seifon** [comment]
> 谢谢提供信息，后面我考虑一下导出pdf的格式。不过pdf貌似比较复杂（拍脑袋的感觉:) ），估计不能很快搞定。

嗯嗯，尽量把样式也导出来额，比如图片缩略图，和视频缩略图这些额

**Comment by qcmuu** [comment]
作者开个赞赏码吧~

**Comment by BlueMatthew** [comment]
> 作者开个赞赏码吧~

感谢 :)

**Comment by BlueMatthew** [comment]
可以试试1.8.0版本，实现了基于chrome/MS edge的pdf导出。不过我自己觉得导出成为pdf，目前的格式过于宽松了，还需要优化

**Comment by BlueMatthew** [comment]
最新的版本，又调整了一下模版，把聊天记录的布局调整得更紧凑些，打印的效果可能会好一些

**Comment by BlueMatthew** [comment]
@Seifon Issue我先关闭了，关于pdf还有其它问题，可以新开issue :)
