### ISSUE TITLE
请问有无关于微信数据各个字段的解析类的文档或者网页？

### ISSUE THREAD

**Issue by Qxxxx** [BlueMatthew/WechatExporter#125]
Hello,

想问下关于微信数据结构的问题，首先我按照征程流程使用iTunes备份了数据，并且使用DB Browser 来查看数据。稍微看了一下代码，我的理解是所有人的聊天记录应该都在`Documents/7c2372c6a8323f5c9f80265e9a5b52b2/DB/MM.sqlite`中，不同人的聊天记录是以不同的`table`以`CHAT_`开头。但当我根据`fileID=478e78f680bb7502f5160aeeeec0c32687daa36c` 找到对应的文件并打开之后，我发现里面的聊天记录非常少，就是以`CHAT_`开头的表特别少，请问我是漏了哪个环节或者理解有哪里出错了嘛？

**Comment by BlueMatthew** [comment]
微信有做分库的处理，你可以看看DB目录下的其它几个库文件
