### ISSUE TITLE
出现导出一半假死的状况

### ISSUE THREAD

**Issue by qcmuu** [BlueMatthew/WechatExporter#13]
您好，我使用昨天刚发布的程序进行导出，出现导出一般就假死的情况。

我所使用的平台是Microsoft Windows [Version 10.0.19042.906]。不知道还有什么信息可以提供给您参考诊断这个问题？

![image](https://user-images.githubusercontent.com/24704891/115119442-f2324600-9fda-11eb-9235-b31041fa0155.png)
![image](https://user-images.githubusercontent.com/24704891/115119467-09713380-9fdb-11eb-9221-2868de2912a9.png)

再次谢谢您的付出

**Comment by BlueMatthew** [comment]
是值19:56:11之后就一直卡住了吗？列表中的小进度条和导出的聊天记录数也停止不变化了吗？

**Comment by BlueMatthew** [comment]
顺便问一个无关的问题，你的windows是英文语言的吗？我看wechat exporter显示了英文，确认一下是不是一致。

**Comment by qcmuu** [comment]
1. 是的，是英文语言。
2. 对的，列表中的小进度条和导出的聊天记录数也停止不变化。我运行了几次，发现似乎对某些特定的群组或人会存在完全卡住这个问题。如果不勾选他们就可以顺利导出。
3. 卡住的时候，CPU的负载还是存在。

**Comment by BlueMatthew** [comment]
> 1. 是的，是英文语言。
> 2. 对的，列表中的小进度条和导出的聊天记录数也停止不变化。我运行了几次，发现似乎对某些特定的群组或人会存在完全卡住这个问题。如果不勾选他们就可以顺利导出。
> 3. 卡住的时候，CPU的负载还是存在。

导出的时候，列表会显示当前导出的记录数和总聊天记录数，你能看一下每次卡住是不是都是同一条消息（可以只选会卡住的聊天群来试）？如果是固定的消息，那可能是当中有一些未知的数据格式未处理正确，如果我提供一个记录数据的版本，把消息记录下来，能麻烦你帮忙看一下其中的特征吗？

**Comment by qcmuu** [comment]
是同一条消息（特定的聊天对象或群组）。
好的，麻烦您提供下。谢谢~

**Comment by BlueMatthew** [comment]
Alex，麻烦用附件wxexp.zip解压出来的程序导出一下会卡住的聊天记录。程序会把当前正在导出的聊天记录数据写在输出目录下的dbg 子目录下，一共会记录下面几个文件：
lastmsgid.txt 消息id
lastmsgtype.txt  消息类型
lastmsgcontent.txt  消息数据
lastappmsg.xml app类型的消息数据 xml格式
lastlocation.xml  定位消息数据 xml格式 （应该可以忽略）

其中消息内容主要是lastmsgcontent.txt和lastappmsg.xml两个文件，等程序卡住不往后面导出的时候，你可以把dbg目录拷贝一份出来，如果要浏览文件是否有敏感信息，你可以把文件拖到浏览器中打开查看（因为是utf8编码，也可是试试windows的文本编辑器是否能正常显示，我不是很确定），如果没有敏感信息，看是否能把内容发给我调试一下，或者把msgtype发一下，我猜测大概率是appmsg的解析有问题。

[wxexp.zip](https://github.com/BlueMatthew/WechatExporter/files/6336770/wxexp.zip)

对应的代码修改在分支 issue13里面
https://github.com/BlueMatthew/WechatExporter/tree/issue13

谢谢啦

**Comment by qcmuu** [comment]
@BlueMatthew Hi Matthew. 好的，我这周末处理下，这周有点忙，不好意思。

**Comment by qcmuu** [comment]
@BlueMatthew 抱歉久等了。这里是导出来的文件。（xml的文件无法直接上传，我把后缀修改了下）
[lastmsgid.txt](https://github.com/BlueMatthew/WechatExporter/files/6379049/lastmsgid.txt)
[lastmsgtype.txt](https://github.com/BlueMatthew/WechatExporter/files/6379050/lastmsgtype.txt)
[lastmsgcontent.txt](https://github.com/BlueMatthew/WechatExporter/files/6379051/lastmsgcontent.txt)
[lastappmsg.xml.txt](https://github.com/BlueMatthew/WechatExporter/files/6379057/lastappmsg.xml.txt)

**Comment by BlueMatthew** [comment]
可以试试 v1.7.20.3，应该修复了

**Comment by qcmuu** [comment]
好的，非常感谢！我这几天有空来试一下。
