### ISSUE TITLE
希望可以在非GPL协议下使用本项目前端资源文件

### ISSUE THREAD

**Issue by Young-Lord** [BlueMatthew/WechatExporter#148]
本人的 [QQ 聊天记录导出](https://github.com/Young-Lord/QQ-History-Backup)计划使用一个限制商用与闭源的[协议](https://github.com/Young-Lord/QQ-History-Backup/blob/dev/LICENSE)，显然与 GPL 不兼容。但又很希望使用您的前端代码，故能否单独批准我以此协议使用？谢谢！

**Comment by Young-Lord** [comment]
啊，算了，我不如改成AGPL吧……

**Comment by Young-Lord** [comment]
但是还有个小问题…… GPLv3 和 GPLv2 是不兼容的，所以可以请求您在 GPLv3 协议下再发布一次本软件吗？或者口头同意一下也好。感谢！

**Comment by BlueMatthew** [comment]
使用里面的html模版？

**Comment by Young-Lord** [comment]
> 使用里面的html模版？

是的

**Comment by BlueMatthew** [comment]
可以使用


Best regards,
Matthew


在 2023年5月9日，下午5:02，LY ***@***.***> 写道：

﻿

使用里面的html模版？

是的

**Comment by Young-Lord** [comment]
好的。感谢！
