### ISSUE TITLE
Failed to parse iTunes Backup file

### ISSUE THREAD

**Issue by Qiaoyf96** [BlueMatthew/WechatExporter#16]
非常感谢您提供的工具！但是我在试图加载 iTunes Backup 时，程序报错“Failed to parse iTunes Backup file”。

我的平台是 MacOS 11.3，尝试了WechatExporter 1.7.20.3 和 1.7.20.2，但都在报这个相同的错误。我导入的路径是 `/Users/yifan/Library/Application\ Support/MobileSync/Backup/00008101-000438810A90001E`。

**Comment by Qiaoyf96** [comment]
抱歉打扰了，路径写到 `Backup` 就好了😂

**Comment by BlueMatthew** [comment]
> 抱歉打扰了，路径写到 `Backup` 就好了😂

汗，回头我也优化一下

**Comment by BlueMatthew** [comment]
对了，默认有没有自动选择路径：/Users/yifan/Library/Application\ Support/MobileSync/Backup/ ？

**Comment by Qiaoyf96** [comment]
是没有的，默认为空，需要我手动选择路径。

**Comment by Qiaoyf96** [comment]
> 对了，默认有没有自动选择路径：/Users/yifan/Library/Application\ Support/MobileSync/Backup/ ？

是没有的，默认为空，需要我手动选择路径。

**Comment by BlueMatthew** [comment]
> > 对了，默认有没有自动选择路径：/Users/yifan/Library/Application\ Support/MobileSync/Backup/ ？
> 
> 是没有的，默认为空，需要我手动选择路径。

呃，我查一下，应该做了这个功能的，估计出bug了，我一直当，如果没有改过itunes store的备份路径的话，选择按钮应该用不着的。。。
