### ISSUE TITLE
支持企业微信吗

### ISSUE THREAD

**Issue by NigelWu95** [BlueMatthew/WechatExporter#181]

**Comment by BlueMatthew** [comment]
企业微信我记得是加密的，不支持。
________________________________
发件人: 吴炳亨 ***@***.***>
发送时间: 2024年7月4日 12:21
收件人: BlueMatthew/WechatExporter ***@***.***>
抄送: Subscribed ***@***.***>
主题: [BlueMatthew/WechatExporter] 支持企业微信吗 (Issue #181)


―
