### ISSUE TITLE
能否支持导出为数据库格式，方便进行可视化的二次开发

### ISSUE THREAD

**Issue by zuston** [BlueMatthew/WechatExporter#19]

**Comment by BlueMatthew** [comment]
微信本身其实就有一个sqlite的消息数据库，只是微信消息类型太多，所以它自己也只能是一个壳，内部很多数据都是通过xml在维护的，蛮难出一个统一的数据库格式呢。

**Comment by zuston** [comment]
当前可以把可视化生成 HTML 需要的数据和消息类型存储为一个 sqlite 文件，不需要全，只需要定义好规范，补充一些文档，这样子以后想要额外的一些数据，也直接可以开发使用。同时也方便其他开发者接入和理解。

不知道有没有表达清楚，主要就是给一个可读可理解的数据库。
举个例子，比如现在我想看到聊天消息的名字或者昵称，其实我就只需要更改下前端的页面即可的话（如果你已经解析出来了）。
但是现在的话，我需要看你的 c++ 代码，看怎么解析的逻辑。其实开发起来就比较耦合了。
