### ISSUE TITLE
选择目录确认完以后没有反应。

### ISSUE THREAD

**Issue by ck167493** [BlueMatthew/WechatExporter#2]
打开后不能选择itunes备份目录，选择目录确认完以后没有反应。测试机器windows 10 pro，x64，cpuamd3600，16Gram，

**Comment by BlueMatthew** [comment]
itunes的版本是什么呢？

**Comment by BlueMatthew** [comment]
> 打开后不能选择itunes备份目录，选择目录确认完以后没有反应。测试机器windows 10 pro，x64，cpuamd3600，16Gram，

因为iTunes的备份目录不是能随意修改的，所以工具启动的时候，会自动到默认的目录中去检查iTunes备份文件，如果启动并没有获取到备份相关的信息，那就说明是失败了，可能是这个版本的iTunes程序不能支持。请你告知一下iTunes版本，需要调试一下。或者是不是iTunes备份的时候设置加密了?

**Comment by ck167493** [comment]
> > 打开后不能选择itunes备份目录，选择目录确认完以后没有反应。测试机器windows 10 pro，x64，cpuamd3600，16Gram，
> 
> 因为iTunes的备份目录不是能随意修改的，所以工具启动的时候，会自动到默认的目录中去检查iTunes备份文件，如果启动并没有获取到备份相关的信息，那就说明是失败了，可能是这个版本的iTunes程序不能支持。请你告知一下iTunes版本，需要调试一下。或者是不是iTunes备份的时候设置加密了?

由于说明的时候没有标注版本，目前我用的是最新的版本。如果您有建议的版本可以post一下吗？谢谢

**Comment by BlueMatthew** [comment]
> > > 打开后不能选择itunes备份目录，选择目录确认完以后没有反应。测试机器windows 10 pro，x64，cpuamd3600，16Gram，
> > 
> > 
> > 因为iTunes的备份目录不是能随意修改的，所以工具启动的时候，会自动到默认的目录中去检查iTunes备份文件，如果启动并没有获取到备份相关的信息，那就说明是失败了，可能是这个版本的iTunes程序不能支持。请你告知一下iTunes版本，需要调试一下。或者是不是iTunes备份的时候设置加密了?
> 
> 由于说明的时候没有标注版本，目前我用的是最新的版本。如果您有建议的版本可以post一下吗？谢谢

我今天Win10上装了iTunes 12.10.10.2试了一下，还是可以的，好像还有一个新版本，12.11，我一会儿也试一下。你如果是最新的，也应该是这两个版本之一吧？

**Comment by BlueMatthew** [comment]
我刚刚增加了一些错误处理，出了版本1.6，如果iTunes解析失败，会有提示信息出来，你可以试试是不是有提示信息。

**Comment by ck167493** [comment]
> 我刚刚增加了一些错误处理，出了版本1.6，如果iTunes解析失败，会有提示信息出来，你可以试试是不是有提示信息。

刚刚下载您最新的试用了一下，我的版本是iTunes 12.10.10.2，选择了目录以后弹出来解释itunes backup失败。

**Comment by ck167493** [comment]
iTunes备份的时候设置加密了，我想问一下如何设置不加密呢？备份处选择本机以后加密本地备份他是默认打勾而且是灰色不可更改的，谢谢。

**Comment by BlueMatthew** [comment]
> 噢，我明白了。我的备份因为有企业描述档，他已经设置为默认加密了。不好意思。我换个手机再试试看吧，谢谢，麻烦你了。
> 然后可以问一下其实ipad的备份也可以用吗？谢谢

我没有测试过，但是应该可以的。

**Comment by ck167493** [comment]
> > 噢，我明白了。我的备份因为有企业描述档，他已经设置为默认加密了。不好意思。我换个手机再试试看吧，谢谢，麻烦你了。
> > 然后可以问一下其实ipad的备份也可以用吗？谢谢
> 
> 我没有测试过，但是应该可以的。

是可以的，太感谢了老哥。我跟我前女友的能复合的话，我一定会来打赏888

**Comment by BlueMatthew** [comment]
> > > 噢，我明白了。我的备份因为有企业描述档，他已经设置为默认加密了。不好意思。我换个手机再试试看吧，谢谢，麻烦你了。
> > > 然后可以问一下其实ipad的备份也可以用吗？谢谢
> > 
> > 
> > 我没有测试过，但是应该可以的。
> 
> 是可以的，太感谢了老哥。我跟我前女友的能复合的话，我一定会来打赏888

哈哈，不用打赏，你已经赋予了这个小工具不一样的价值 :)，祝你成功！

有其它问题，尽管发到这儿。
