### ISSUE TITLE
放到服务器上实在是没法用，太卡了太占资源，就算本地跑都很卡

### ISSUE THREAD

**Issue by MaLin1997** [BlueMatthew/WechatExporter#22]
建议参考一下 http://wxbackup.imxfd.com/ 的方案

**Comment by BlueMatthew** [comment]
设置成滑动时加载也很卡是吗？

不过因为数据都是在主文件中的，可能是会卡一些，原先我个人的目的主要还是自己备份，在本机上浏览，所以感觉还好:)。 后面有时间会考虑把数据也独立出来。

**Comment by jinuljt** [comment]
或许可以考虑一下使用类似 [sql.js](https://sql.js.org/) 这种sqlite的实现方式。

**Comment by BlueMatthew** [comment]
这几天我已经在改造模版文件了，以js动态加载消息，应该可以解决这个问题了。代码基本改好了，不过还没有最后出一个build。

**Comment by MaLin1997** [comment]
> 这几天我已经在改造模版文件了，以js动态加载消息，应该可以解决这个问题了。代码基本改好了，不过还没有最后出一个build。

加油

**Comment by BlueMatthew** [comment]
> > 这几天我已经在改造模版文件了，以js动态加载消息，应该可以解决这个问题了。代码基本改好了，不过还没有最后出一个build。
> 
> 加油

issue #29中，我放了一个包含最新代码的alpha程序，其中把异步加载改成多个js的分布加载（目前一个js包含500条消息），你可以试试看，是不是放到服务器上效果会好很多（滑动到底部再加载更多数据的模式）

**Comment by MaLin1997** [comment]
> > > 这几天我已经在改造模版文件了，以js动态加载消息，应该可以解决这个问题了。代码基本改好了，不过还没有最后出一个build。
> > 
> > 
> > 加油
> 
> Issue #29中，我放了一个包含最新代码的alpha程序，其中把异步加载改成多个js的分布加载（目前一个js包含500条消息），你可以试试看，是不是放到服务器上效果会好很多（滑动到底部再加载更多数据的模式）
> 
> #29

好的，我试试

**Comment by BlueMatthew** [comment]
关闭本issue，如有新问题，请新开.
