### ISSUE TITLE
提示“解析itunes backup"失败

### ISSUE THREAD

**Issue by esinhee** [BlueMatthew/WechatExporter#23]
Windows10 21H1下，用itunes 12.11.3.17从ipad导出备份，但是选择备份目录的时候提示“解析itunes backup"失败，请问是什么原因呢？
![捕获](https://user-images.githubusercontent.com/1036181/123015829-d6dd2000-d3fb-11eb-8296-a2cd36c1f3e8.JPG)

**Comment by BlueMatthew** [comment]
我做了一个打印错误信息的版本，你再执行一下，报错之后，点显示日志按钮，看看右边日志框有什么错误信息呢。
[dbg.zip](https://github.com/BlueMatthew/WechatExporter/files/6698719/dbg.zip)

**Comment by esinhee** [comment]
> 
> 
> 我做了一个打印错误信息的版本，你再执行一下，报错之后，点显示日志按钮，看看右边日志框有什么错误信息呢。
> [dbg.zip](https://github.com/BlueMatthew/WechatExporter/files/6698719/dbg.zip)

没有输出日志。
选择备份目录之后马上报错，是系统的问题吗？

**Comment by BlueMatthew** [comment]
看到报错对话框，点确定按钮之后，在点界面左下角的显示日志按钮，会切换到日志界面，那里也没有任何信息吗？

**Comment by esinhee** [comment]
> 
> 
> 看到报错对话框，点确定按钮之后，在点界面左下角的显示日志按钮，会切换到日志界面，那里也没有任何信息吗？

抱歉，昨天忙，没有及时回复。
提示错误之后，点日志没有任何内容。

**Comment by esinhee** [comment]
`	LRESULT OnBnClickedChooseBkp(WORD /*wNotifyCode*/, WORD /*wID*/, HWND /*hWndCtl*/, BOOL& /*bHandled*/)
	{
		CString text;
		text.LoadString(IDS_SEL_BACKUP_DIR);

		CFolderDialog folder(NULL, text, BIF_RETURNONLYFSDIRS | BIF_USENEWUI | BIF_NONEWFOLDERBUTTON);
		if (IDOK == folder.DoModal())
		{
			CW2A backupDir(CT2W(folder.m_szFolderPath), CP_UTF8);

			ManifestParser parser((LPCSTR)backupDir);
			std::vector<BackupManifest> manifests;
			if (parser.parse(manifests) && !manifests.empty())
			{
				UpdateBackups(manifests);
#ifndef NDEBUG
				AppConfiguration::SetLastBackupDir(folder.m_szFolderPath);
#endif
			}
			else
			{
				m_logger->debug(parser.getLastError());
				MsgBox(m_hWnd, IDS_FAILED_TO_LOAD_BKP);
			}
		}

		return 0;
	}`
看了一下，这段代码是走else分支了。

**Comment by BlueMatthew** [comment]
是的，执行到这两句代码了：
m_logger->debug(parser.getLastError());
MsgBox(m_hWnd, IDS_FAILED_TO_LOAD_BKP);

上次的dbg.zip就是把m_logger->debug(parser.getLastError()); 的条件编译去掉了，不过忘记把debug函数内的条件编译也一起去掉，所以导致日志没有输出，惭愧。

晚点我再看看这个处理过程中还有什么遗漏的，然后把debug函数的条件编译也去掉，再出一个执行文件请你看看。

**Comment by BlueMatthew** [comment]
[dbg20210624.zip](https://github.com/BlueMatthew/WechatExporter/files/6707822/dbg20210624.zip)

空了再执行一下这个程序呢，应该会输出日志吧

**Comment by esinhee** [comment]
> 
> 
> [dbg20210624.zip](https://github.com/BlueMatthew/WechatExporter/files/6707822/dbg20210624.zip)
> 
> 空了再执行一下这个程序呢，应该会输出日志吧

试了两次
`
17:56:52.126: [DBG] Info.plist not found
Manifest.db not found
No valid backup id found in:C:\Users\QHEE\AppData\Roaming\Apple Computer\MobileSync\Backup

17:57:24.448: [DBG] Manifest.db not found
No valid backup id found in:C:\Users\QHEE\AppData\Roaming\Apple Computer\MobileSync\Backup\e5b73360208baf46df23629f285d877abbe79a31
`

**Comment by BlueMatthew** [comment]
问题应该在第二部分。先看看 C:\Users\QHEE\AppData\Roaming\Apple Computer\MobileSync\Backup\e5b73360208baf46df23629f285d877abbe79a31 确实是你的备份目录吗？
然后看看 目录下的文件类似下面截屏中的吗？ 

![backup](https://user-images.githubusercontent.com/37573096/123244949-f4eb7300-d516-11eb-9f34-a6bba4753ba6.png)

**Comment by esinhee** [comment]
> 
> 
> 问题应该在第二部分。先看看 C:\Users\QHEE\AppData\Roaming\Apple Computer\MobileSync\Backup\e5b73360208baf46df23629f285d877abbe79a31 确实是你的备份目录吗？
> 然后看看 目录下的文件类似下面截屏中的吗？
> 
> ![backup](https://user-images.githubusercontent.com/37573096/123244949-f4eb7300-d516-11eb-9f34-a6bba4753ba6.png)
是备份目录的问题，不知道为什么备份出来的是下面这样的。我试试把iTunes重装看看。
![图片](https://user-images.githubusercontent.com/1036181/123350095-dde76800-d58c-11eb-85e6-1480b91702c7.png)

**Comment by esinhee** [comment]
试了两台电脑，不同版本的iTunes，备份出来的目录结构都是一样的。会不会是iOS版本的问题，我的是9.3.6

**Comment by BlueMatthew** [comment]
> 试了两台电脑，不同版本的iTunes，备份出来的目录结构都是一样的。会不会是iOS版本的问题，我的是9.3.6

我找个ios9试试

**Comment by BlueMatthew** [comment]
确实是ios 9的备份出来的文件格式不一样，之前实现的时候，这部分没有做，我再补一下

**Comment by esinhee** [comment]
> 
> 
> 确实是ios 9的备份出来的文件格式不一样，之前实现的时候，这部分没有做，我再补一下

兄弟，辛苦了

**Comment by BlueMatthew** [comment]
[dbg20210626.zip](https://github.com/BlueMatthew/WechatExporter/files/6720002/dbg20210626.zip)

找到一个ios9的设备，可是新装的微信，7.0.2，微信已经已经不让登录了，所以只能把代码实现了，没法实际测试。你有空了，麻烦试试附件的程序，看能否导出呢。

**Comment by esinhee** [comment]
> 
> 
> 确实是ios 9的备份出来的文件格式不一样，之前实现的时候，这部分没有做，我再补一下

请求编译一版最新的，谢谢。

**Comment by BlueMatthew** [comment]
> > 确实是ios 9的备份出来的文件格式不一样，之前实现的时候，这部分没有做，我再补一下
> 
> 请求编译一版最新的，谢谢。

前两天改的还有点问题，我还在调试，今天晚上应该能出来

**Comment by BlueMatthew** [comment]
[dbg20210629.zip](https://github.com/BlueMatthew/WechatExporter/files/6727885/dbg20210629.zip)

有空帮忙试试这个程序是不是可以，谢谢。

**Comment by esinhee** [comment]
> 
> 
> [dbg20210629.zip](https://github.com/BlueMatthew/WechatExporter/files/6727885/dbg20210629.zip)
> 
> 有空帮忙试试这个程序是不是可以，谢谢。

备份的目录可以自动加载了，不过聊天记录似乎没有解析出来。开始以为备份里没有微信，又重新备份了一次，还是一样。
![图片](https://user-images.githubusercontent.com/1036181/123718623-3c288980-d8b2-11eb-8c50-c025ae615e93.png)
![图片](https://user-images.githubusercontent.com/1036181/123718649-506c8680-d8b2-11eb-870d-b41db54efadb.png)

**Comment by BlueMatthew** [comment]
我想想办法看怎么能让微信7.0.2登录进去

**Comment by BlueMatthew** [comment]
[dbg20210629-2.zip](https://github.com/BlueMatthew/WechatExporter/files/6731178/dbg20210629-2.zip)

我自己测试过了，应该可以，不过数据比较少。你空了试试看。

**Comment by esinhee** [comment]
> 
> 
> [dbg20210629-2.zip](https://github.com/BlueMatthew/WechatExporter/files/6731178/dbg20210629-2.zip)
> 
> 我自己测试过了，应该可以，不过数据比较少。你空了试试看。

这个版本可以了，导出来也没有问题。非常感谢

**Comment by BlueMatthew** [comment]
> > [dbg20210629-2.zip](https://github.com/BlueMatthew/WechatExporter/files/6731178/dbg20210629-2.zip)
> > 我自己测试过了，应该可以，不过数据比较少。你空了试试看。
> 
> 这个版本可以了，导出来也没有问题。非常感谢

那就好 :)

**Comment by BlueMatthew** [comment]
Issue我先关闭了，后面有其它问题可以新开issue
