### ISSUE TITLE
请问是否支持windows 原生微信聊天记录查看

### ISSUE THREAD

**Issue by xiaowuzimaxhub** [BlueMatthew/WechatExporter#25]
作者 您好,请问 我在 win 10 下把 C:/Users/用户名/Documents/WeChat Files/微信id/ 文件夹下的内容复制了出来,请问该软件是否支持直接浏览查看?如果 我只能有这种方式 请问我该如何使用该软件查看，谢谢
<img width="236" alt="wechat" src="https://user-images.githubusercontent.com/5202715/123500025-91278e00-d66d-11eb-9fd0-44890d2f1a64.png">

**Comment by BlueMatthew** [comment]
你这是windows pc的数据文件，里面都是加密的哦。这个程序是不能解析的。必须通过iphone或者ipad由iTunes备份（未加密方式），然后才能把手机或者ipad上的微信聊天记录导出来。

**Comment by BlueMatthew** [comment]
另外，微信现在可以没有手机登录，而只是pc版本登录了吗？

**Comment by xiaowuzimaxhub** [comment]
> 你这是windows pc的数据文件，里面都是加密的哦。这个程序是不能解析的。必须通过iphone或者ipad由iTunes备份（未加密方式），然后才能把手机或者ipad上的微信聊天记录导出来。

好的，谢谢哈。

**Comment by xiaowuzimaxhub** [comment]
> 另外，微信现在可以没有手机登录，而只是pc版本登录了吗？

这是我之前用的公司的PC ，离职了只能复制出来了哈。

**Comment by BlueMatthew** [comment]
网上有一些讨论微信pc版本数据加解密的东西，你可以找找看

> > 另外，微信现在可以没有手机登录，而只是pc版本登录了吗？
> 
> 这是我之前用的公司的PC ，离职了只能复制出来了哈。
