### ISSUE TITLE
如何进行增量备份。这是我见过的最好的备份了。

### ISSUE THREAD

**Issue by bovey1** [BlueMatthew/WechatExporter#26]
首先点赞。这个程序虽然繁琐需要连接电脑备份iPhone。但是生成的文件非常好。有语音还有图片。
对于空间小的iPhone用户就是福利。强烈推荐。有空写个博客做个视频推荐一下。

但是如果我删除了我的微信再次下载（这个可以彻底清除数据，减少容量）。过几个月再次备份 是不是就只能新生产一个文件夹。

如果能增加增量备份就好了。

这个系统可以进行 检索。文字检索也好。建议增加这2个功能。或者我不知道在哪？希望有人告知

**Comment by BlueMatthew** [comment]
增量备份我考虑一下，看看要怎么管理

检索目前做了一个简单的支持，你可以通过菜单上的选项打开

**Comment by BlueMatthew** [comment]
[IncExp.zip](https://github.com/BlueMatthew/WechatExporter/files/6856261/IncExp.zip)

你提的需求，有空帮忙测试测试，看看增量导出有没有问题（要选择一下菜单：选项\增量导出）

**Comment by BlueMatthew** [comment]
关闭本issue，如有问题，请新开。
