### ISSUE TITLE
希望作者出一个针对已经解开iOS备份的版本

### ISSUE THREAD

**Issue by lazybug163** [BlueMatthew/WechatExporter#27]
当前版本设计是针对iTunes的备份，但是iTunes备份往往是整机的数据，非常大
我之前做过几次用其他工具把iTunes备份解开，只保留备份wechat的目录
所以希望作者出一个针对已经解开iOS备份的版本
个人理解代码上实现应该并不复杂吧，做一个编译开关是不是就可以了吧，麻烦作者考虑一下哈，谢谢

**Comment by BlueMatthew** [comment]
确实，实现这个应该是简单的。不过操作交互上会存在一些问题，目前导出只需要确定iTunes的备份目录即可，而且程序尽量自动找到了这个备份目录，对于一般的用户来说，特别是电脑操作不那么熟悉的，相对是更简单的。另外，微信的新版本把数据存放到了两个app（属于同一个group）中，你们通过iMazing/iTools之类的工具把微信app的文件导出的时候，要记得导出所有相关的。而对于本工具来说，就需要用户选择两个目录，这增加了用户操作的麻烦度。而且我个人其实不那么信任iMazing/iTools之类的工具，虽然我以前也偶尔用过。 :)

如果需要的话，我可以开个分支，简单处理一下来实现你这样的需求，不过主分支暂时应该不会加。

**Comment by lazybug163** [comment]
哦，原来如此。不过还是麻烦作者开个分支出一个版本，我当小白鼠验证一下哈，谢谢啦

**Comment by BlueMatthew** [comment]
你导出的微信文件的目录结构是这样的吗？
![folders](https://user-images.githubusercontent.com/37573096/125907917-b158f2b0-ebdf-4db9-ae57-64dd12bcc24b.png)

**Comment by lazybug163** [comment]
不是，我的备份数据大都是2019年以前的，老的6s备份出来的
直接只备份了Documents目录：
![wechatbackup](https://user-images.githubusercontent.com/87252505/125965870-cb78a56e-83a4-4169-a8f5-17f169a53e9c.png)

**Comment by BlueMatthew** [comment]
明白了。等我实现好增量备份，到时候给你弄个 :)

**Comment by lazybug163** [comment]
好，多谢，好饭不怕晚哈

**Comment by BlueMatthew** [comment]
Branch: DecodedITunes

[DecodedITunes.zip](https://github.com/BlueMatthew/WechatExporter/files/6856252/DecodedITunes.zip)
我简单测试了一下，你试试你备份出来的文件，能不能导出聊天记录。

**Comment by lazybug163** [comment]
可以工作，我导出试试，找找bug哈，多谢

**Comment by BlueMatthew** [comment]
有个比较严重的html异步加载的bug，更新一下程序

[DecodedITunes.zip](https://github.com/BlueMatthew/WechatExporter/files/6871697/DecodedITunes.zip)

**Comment by lazybug163** [comment]
多谢，这2个版本都可以工作。
bug目前还没找到啥，有个小建议：时间的显示可以不用am、pm不？这是英美人的习惯，咱们看到12:00pm往往还得琢磨是半夜呢还是中午。。。哈哈，不如直接24小时显示
另外，通过这个工具，除了我备份出来的重要信息之外，还发现有些信息貌似是被删除掉了，通过sql工具搜也极其费力，咱们这有没有啥办法？

**Comment by BlueMatthew** [comment]
> 多谢，这2个版本都可以工作。
> bug目前还没找到啥，有个小建议：时间的显示可以不用am、pm不？这是英美人的习惯，咱们看到12:00pm往往还得琢磨是半夜呢还是中午。。。哈哈，不如直接24小时显示

好，后面一个版本调整一下

> 另外，通过这个工具，除了我备份出来的重要信息之外，还发现有些信息貌似是被删除掉了，通过sql工具搜也极其费力，咱们这有没有啥办法？

一些信息被删除了是指某个聊天没有被导出来呢，还是某个聊天中的部分消息没有导出来？目前一个聊天中的消息如果类型不能识别的，会尽量转成一个文本信息，但是好像没有丢弃。有更具体一些的信息吗？sql工具费力是指找不到对应的表吗？

**Comment by lazybug163** [comment]
"某个聊天中的部分消息没有导出来" => 这个貌似有，因为我发现有个别记录不是从头开始的，sql里应该有，可能是类型识别的问题，不知道有没有可能合并显示出来？
另外还发现有部分记录里时间线断了很久。
"sql工具费力是指找不到对应的表" => 太对了，我是做商务的，上千个联系人和群，sql表巨复杂无比，搜索了半小时就放弃了。
哦，最麻烦的，被删除的联系人和聊天记录有没有可能找回来呢？我看有些收费软件可以做到，可是试用版看着不靠谱

**Comment by BlueMatthew** [comment]
> "某个聊天中的部分消息没有导出来" => 这个貌似有，因为我发现有个别记录不是从头开始的，sql里应该有，可能是类型识别的问题，不知道有没有可能合并显示出来？
> 另外还发现有部分记录里时间线断了很久。
> "sql工具费力是指找不到对应的表" => 太对了，我是做商务的，上千个联系人和群，sql表巨复杂无比，搜索了半小时就放弃了。
> 哦，最麻烦的，被删除的联系人和聊天记录有没有可能找回来呢？我看有些收费软件可以做到，可是试用版看着不靠谱

关于确实消息的问题，回头我看看再增加一些数据写到导出的页面中，不过也只能核对数据库中的消息数量和导出的消息数量是否一致。我还是在最初的一些版本，有仔细核对微信的聊天记录和导出的聊天记录是否一致，最近的一些版本还确实没有仔细测试了，正好你核对了，可以测试一下最新的代码 :) 另外，我把不认识的消息的记录日志也放开来。

新版本的微信做了分表处理，感觉一些删除的聊天记录的数据还是在的，因为我自己好像有一个群，微信里找不到了，但是每次导出好像又在，回头我仔细再看看，不过你可以多看看那些名字类似wxid_xxxxxxxx的，是不是之前删除掉的呢。

你要找某个聊天记录，是想备份这个聊天记录呢，还是想找某条聊天的消息？

**Comment by lazybug163** [comment]
我也不知道我要具体找啥 毕竟用了5年的6s 微信里的东西也是来回折腾 能找回多少就多少吧 要不我干嘛备份整个文件夹呢 呵呵
我还是建议，如果可能的话，尽可能把所有数据库的信息都展示出来，没有关联的就找个通用地方存着呗，看看是不是可行哈

**Comment by BlueMatthew** [comment]
我后来看了看实现，消息应该是全部导出来了的，选择列表中的消息数这列就是表里面的记录数量。附件我在日志里输入了DB文件名和表名，你可以对你觉得有问题的，对照sqlite表核对一下呢。
[DecodedITunes-20210728.zip](https://github.com/BlueMatthew/WechatExporter/files/6893265/DecodedITunes-20210728.zip)

另外，目前只是把公众号的数据过滤掉了，至于是不是还有可能删除的聊天还有数据存在，我后面要再看看

**Comment by lazybug163** [comment]
名称那一列里没有看到类似"wxid_xxxxxxxx"的名字啊，所以删除了的联系人对应的聊天记录是不是sql表里也清除了？可是我记得之前用别的微信工具貌似看到wxid_xxx类似的，奇怪

我觉得应该有聊天记录没倒完整，因为我清楚的记得一件事，然后我拿关键字去导出目录里用FileLocatorPro搜索确实没找到 :(

公众号的数据过滤完全没问题哈

我回头用整个带log的版本再跑一下试试

**Comment by lazybug163** [comment]
22:26:14: [DBG] ITunes Database loaded.
22:26:14: 查找微信登录账户...
22:26:14: 找到 1个账号的消息记录。
22:26:14: 读取账号信息
22:26:14: 读取对话信息
22:26:20: [DBG] Wechat Friends(25118) for:  loaded.

22:26:30: 1010/18120: 处理与 ABC 的对话
22:26:32: 成功处理198条消息
22:26:32: 1012/18120: 处理与 DCEF 的对话
22:26:34: 成功处理212条消息

DB文件名log里没看到，ABC就是微信的名字，也是表名，还是没有wxid_XXXX的，数据库里我记得是有的

**Comment by BlueMatthew** [comment]
[DecodedITunes-20210730.zip](https://github.com/BlueMatthew/WechatExporter/files/6907021/DecodedITunes-20210730.zip)
再试试这个看呢，我把存在在消息库，但是不在聊天session库的也取出来了，看看是不是有删除的。

**Comment by lazybug163** [comment]
嗯，看到一些"-deleted"的名称了，可是导出有问题
我按照聊天记录数排序，然后先后找最多数的"-deleted"和一个显示说有4条记录"-deleted"，导出之后，发现导出的东西是完全一样的，日志里也显示查询了一堆的表项

**Comment by BlueMatthew** [comment]
> 嗯，看到一些"-deleted"的名称了，可是导出有问题
> 我按照聊天记录数排序，然后先后找最多数的"-deleted"和一个显示说有4条记录"-deleted"，导出之后，发现导出的东西是完全一样的，日志里也显示查询了一堆的表项

估计是这部分聊天找不到唯一的id，和之前的逻辑冲突了。我改了一下，不过我这边造不出这种数据，你再试试看呢。

23:07:50.708: 28/41: Handling the chat with 张三
23:04:15.555: [DBG] DB: D:\Documents\WxExp\Wechat7.0.2 122510\Documents\********23d14055289a5969a5de248d\DB\MM.sqlite Table: Chat_*************9ffef9691f1fb93996
表名

这个日志就是表示，张三的聊天记录的数据是在MM.sqlite这个数据库中，表名是： Chat_*************9ffef9691f1fb93996
你装一个sqlite 客户端工具，可以直接打开看具体的聊天记录的，当然一部分数据是能直接看懂的，一部分是xml数据。

**Comment by lazybug163** [comment]
这个版本有意思 wxid_unknown_xxx都出来了 
我大致过了一遍 这些基本都是以前老的公众号，以及qq代收的消息，我也找到一些有用的信息，厉害哈
不过，删除的信息貌似还是没找到，我清楚的记得之前拿别的微信工具看到过部分删除的信息的，这些信息存哪了呢？
回头我看看能不能找找支持sql搜索的工具，我大致记得几个客户的关键词来帮忙确认是不是删除的信息

**Comment by lazybug163** [comment]
最开始用"楼月微信聊天记录导出恢复助手"，现在咱这个开源的软件基本达到其功能了，厉害！
我之前还用过一个软件，可以列出来删除的，忘记名字了，电脑上也找不到了

另外，sqlitebrowser不好用啊，不够直观，有没有好用的sql工具推荐啊？

**Comment by BlueMatthew** [comment]
> 这个版本有意思 wxid_unknown_xxx都出来了
> 我大致过了一遍 这些基本都是以前老的公众号，以及qq代收的消息，我也找到一些有用的信息，厉害哈
> 不过，删除的信息貌似还是没找到，我清楚的记得之前拿别的微信工具看到过部分删除的信息的，这些信息存哪了呢？
> 回头我看看能不能找找支持sql搜索的工具，我大致记得几个客户的关键词来帮忙确认是不是删除的信息

wxid_unknown_xxxx是存在聊天数据的数据库表（MM.sqlite中的Chat_xxxxxxxxx），但是在session.db中不存在记录的，也导了出来，我自己感觉是全部导出来了，如果还有删除掉的聊天记录的数据，那就是超出我目前的认知了 ...


> 最开始用"楼月微信聊天记录导出恢复助手"，现在咱这个开源的软件基本达到其功能了，厉害！
> 我之前还用过一个软件，可以列出来删除的，忘记名字了，电脑上也找不到了
> 
> 另外，sqlitebrowser不好用啊，不够直观，有没有好用的sql工具推荐啊？

你想要的直观是指怎么样的功能 :) 我自己理解数据库的客户端工具都差不多的，都不能解读业务性质的数据 。。。

**Comment by BlueMatthew** [comment]
[DecodedITunes-20210806.zip](https://github.com/BlueMatthew/WechatExporter/files/6940615/DecodedITunes-20210806.zip)

修复了群聊名字不能解析的问题，应该大部分都能解析出来了。

**Comment by lazybug163** [comment]
mm.sqlite 2.33GB
brandmsg.db 1.69GB
message.db 1.36GB
ft_message.db 495MB
4987.dftemp 75.9MB
wc005_008.db 6.61MB
session.db 3.96MB/3.92MB
我翻了一下备份目录下相关的大文件，看看能给出啥信息不 :)

**Comment by lazybug163** [comment]
我看了一下你的log，发现所有的信息都是基于MM.sqlite里的吧 :)
开心盒子公司的那个苹果恢复大师，貌似可以找出不少被删除的东西，但是也有一些是错误的，哈哈，不知道他们是扫描哪个文件来获得的。按说sql的写入操作，删除的时候只应该做个标记啊，内容应该还在sql里啊

**Comment by BlueMatthew** [comment]
> 我看了一下你的log，发现所有的信息都是基于MM.sqlite里的吧 :)
> 开心盒子公司的那个苹果恢复大师，貌似可以找出不少被删除的东西，但是也有一些是错误的，哈哈，不知道他们是扫描哪个文件来获得的。按说sql的写入操作，删除的时候只应该做个标记啊，内容应该还在sql里啊

是的，目前消息数据都是存储在MM.sqlite这个文件和后续版本的分表中，如果要找删除的消息，这应该是另外一个主题，也是基于你提到的，删除数据先是做标记，技术上肯定能找到一些，但是因为还会复用，所以必然有一些数据是不完整的或者找不到的。sqlite这方面的讨论应该也有很多的吧。

brandmsg.db和message.db（是brandTimelineMsg 目录下的吧？）应该都是和公众号相关的消息数据，wc005_008应该是朋友圈的数据，session.db就是我们在使用的聊天群的数据（不是消息数据）。

**Comment by lazybug163** [comment]
哈 我想我明白了 我如果要找被删除的 其实得利用sqlite的原理是恢复数据库里的东西
这就变成了另外一个难度很大的问题
难怪很多这方面的工具都是收费的
另外一个想法：如果找到工具把mm.sqlite文件里被删除的记录给修复了，然后再用咱这个工具是不是能展示出来呢 :)

**Comment by BlueMatthew** [comment]
> 哈 我想我明白了 我如果要找被删除的 其实得利用sqlite的原理是恢复数据库里的东西
> 这就变成了另外一个难度很大的问题
> 难怪很多这方面的工具都是收费的
> 另外一个想法：如果找到工具把mm.sqlite文件里被删除的记录给修复了，然后再用咱这个工具是不是能展示出来呢 :)

如果恢复了 肯定可以导出的

sqlite我看了一下恢复的原理貌似不是很难 你可以找找开源的工具 应该不会比收费的做的差 其实我感觉空间应该不多 ：）

**Comment by lazybug163** [comment]
求推荐开源的工具
我找了几个 elite/doctor/systool 貌似都不行。。。

**Comment by lazybug163** [comment]
找了几个，基本都是不完全版本，这个主题貌似不活跃啊
https://github.com/alitrack/undark
	 Undark - a SQLite recovery tool for deleted data or corrupt database 
https://github.com/mdegrazia/SQLite-Deleted-Records-Parser
	 Script to recover deleted entries in an SQLite database 
https://github.com/aramosf/recoversqlite
	 recover deleted information from sqlite files. 
https://github.com/AdotDdot/SQLiteRet
	 Recover deleted data from SQLite databases (python)
https://github.com/ehsanedalat/SQLiteRecovery
	 an extensible C# project for retrieving deleted and not-deleted records from SQLite DB in Android & iOS

**Comment by BlueMatthew** [comment]
> 找了几个，基本都是不完全版本，这个主题貌似不活跃啊
> https://github.com/alitrack/undark
> Undark - a SQLite recovery tool for deleted data or corrupt database
> https://github.com/mdegrazia/SQLite-Deleted-Records-Parser
> Script to recover deleted entries in an SQLite database
> https://github.com/aramosf/recoversqlite
> recover deleted information from sqlite files.
> https://github.com/AdotDdot/SQLiteRet
> Recover deleted data from SQLite databases (python)
> https://github.com/ehsanedalat/SQLiteRecovery
> an extensible C# project for retrieving deleted and not-deleted records from SQLite DB in Android & iOS

应该还是因为个小众需求吧，老实说，我也是你提起删除掉的数据，才到网上搜了一下这方面的信息的 :)

对了，如果你确实有很多删除的消息想找回来的，还可以看看 ft_message.db这个数据库，我备份出来的是fts_message.db，我猜测就是你提到的ft_message,看下来都是文字型的消息，猜测是为了通知所使用的数据。看看是不是有你想找回的消息。

**Comment by lazybug163** [comment]
fts_message.db 我用sqlite expert报错打不开 你用什么工具打开的

**Comment by lazybug163** [comment]
fts_message.db 我用sqlite expert报错打不开 你用什么工具打开的

BTW: mm.sqlite 2.33GB，我用sqlite expert做了一下vacuum，文件大小变小为600MB。。。。

**Comment by BlueMatthew** [comment]
> fts_message.db 我用sqlite expert报错打不开 你用什么工具打开的

我用的工具是DB Browser for SQLite，macos下的，能打开 fts_msaage.db，里面主要的表是 fts_message_table_0_content这样的
按理sqlite expert也一样能打开吧

**Comment by BlueMatthew** [comment]
> fts_message.db 我用sqlite expert报错打不开 你用什么工具打开的
> 
> BTW: mm.sqlite 2.33GB，我用sqlite expert做了一下vacuum，文件大小变小为600MB。。。。

那是不是说明你能找回的消息很多 :)

**Comment by lazybug163** [comment]
看fts_msaage.db看得眼睛都快瞎了 这里面不是notification用到的数据吧 感觉是所有消息啊
那问题来了 这些消息可以整合进咱这个软件不 哈哈哈

**Comment by BlueMatthew** [comment]
> 看fts_msaage.db看得眼睛都快瞎了 这里面不是notification用到的数据吧 感觉是所有消息啊
> 那问题来了 这些消息可以整合进咱这个软件不 哈哈哈

 找到一篇文章，对这个数据库分析的比较透彻，你可以看看，https://cloud.tencent.com/developer/news/28809
应该说消息和MM.sqlite里面是一致的吧，如果需要，可以帮你写一些简单脚本导出来

**Comment by lazybug163** [comment]
那辛苦一下吧 最好把wx_id也对应上哈 如果找不到就用unknownXX表示 不知道可行不

**Comment by lazybug163** [comment]
微信数据库出问题应该也称不上是个小概率事件了，据不知道可不可靠的资料显示，损坏比例约为0.02%，万里挑二。出问题的原因大约包括设备空间不足、电量不足、文件同步失败。 => 这个其实很让人崩溃的，如今时代最重要的其实是数据，我之所以6s用了5年多，还是怕it人士把数据存储和转换做不好，尽量拖着。结果换手机的时候，还是觉得丢了数据，哎

**Comment by lazybug163** [comment]
和主数据库不同，没有把每个人单独分在一个表里，而是所有人分成10个表进行存放，里面的字段主要有c0UsernameID，c1MesLocalID，c2CreateTime，c3Message，第一个的id不是md5值，而是普通的数字，而其余三个都与前面说的一样，似乎有希望。usernameID到底是什么呢，注意到数据库里还有一个表fts_username_id，打开看一看。 => 这里说的不准确，其实是微信把所有人分成10部分，每部分进一个表里而已，倒数据的时候可以用过滤，可是wx_id要跟微信名字对应起来还是挺麻烦。。。

**Comment by BlueMatthew** [comment]
关闭本issue，如果有新问题，可以再提。
