### ISSUE TITLE
导出的有些不显示群聊名称，显示的是@chartroomid

### ISSUE THREAD

**Issue by xietiaoda** [BlueMatthew/WechatExporter#29]
导出的有些不显示群聊名称，显示的是@chartroomid。搜索某些群聊记录时会非常困难，这个有没有解决方法？

**Comment by BlueMatthew** [comment]
应该是这些聊天群的聊天信息找不到了。不过最新的main分支上，我又调整了一些寻找群名字的代码，还没有最后测试完成，你可以先试试这个alpha版本，看看原先显示为@chatroom的能否显示正确的名字，如果还没有的话，可能就比较难找到了，需要具体分析。

[v1.9.0-alpha-20210803.zip](https://github.com/BlueMatthew/WechatExporter/files/6917945/v1.9.0-alpha-20210803.zip)

**Comment by xietiaoda** [comment]
> 应该是这些聊天群的聊天信息找不到了。不过最新的main分支上，我又调整了一些寻找群名字的代码，还没有最后测试完成，你可以先试试这个alpha版本，看看原先显示为@ChatRoom的能否显示正确的名字，如果还没有的话，可能就比较难找到了，需要具体分析。
> 
> [v1.9.0-alpha-20210803.zip](https://github.com/BlueMatthew/WechatExporter/files/6917945/v1.9.0-alpha-20210803.zip)

**Comment by xietiaoda** [comment]
@BlueMatthew 大神，alpha版本仍无法解决。应该不是这些群的聊天信息找不到，因为都是常用的群，且有命名的。看看是否能优化，我可以帮忙测试！

**Comment by BlueMatthew** [comment]
好的，后面几天我仔细调一下看看是不是有什么地方漏掉了。

**Comment by BlueMatthew** [comment]
确实有一个文件路径处理是存在问题的，之前自己的导出，因为需要的都解析出来了，所有后面一些没有解析出来的就没有在意，汗。修正的版本在我自己的测试中，除了少数几个之外，都解析出名字了。你可以试试。

少数几个还没有导出的，我后面再查查。

[v1.9.0-alpha.2-20210806.zip](https://github.com/BlueMatthew/WechatExporter/files/6940551/v1.9.0-alpha.2-20210806.zip)

**Comment by BlueMatthew** [comment]
v1.8.0.9也修复了这个问题

**Comment by xietiaoda** [comment]
> 确实有一个文件路径处理是存在问题的，之前自己的导出，因为需要的都解析出来了，所有后面一些没有解析出来的就没有在意，汗。修正的版本在我自己的测试中，除了少数几个之外，都解析出名字了。你可以试试。
> 
> 少数几个还没有导出的，我后面再查查。
> 
> [v1.9.0-alpha.2-20210806.zip](https://github.com/BlueMatthew/WechatExporter/files/6940551/v1.9.0-alpha.2-20210806.zip)

这个版本绝大部分可以显示名称了，少数仍显示@chatroomid，请大神有时间继续攻坚克难！为大神的作品点赞，这是我见过最好的备份了。

**Comment by BlueMatthew** [comment]
> > 确实有一个文件路径处理是存在问题的，之前自己的导出，因为需要的都解析出来了，所有后面一些没有解析出来的就没有在意，汗。修正的版本在我自己的测试中，除了少数几个之外，都解析出名字了。你可以试试。
> > 少数几个还没有导出的，我后面再查查。
> > [v1.9.0-alpha.2-20210806.zip](https://github.com/BlueMatthew/WechatExporter/files/6940551/v1.9.0-alpha.2-20210806.zip)
> 
> 这个版本绝大部分可以显示名称了，少数仍显示@chatroomid，请大神有时间继续攻坚克难！为大神的作品点赞，这是我见过最好的备份了。

还是 @stomakun 原始版本的基础好

**Comment by yemelody** [comment]
iTunes版本：12.11.3.17, iOS版本：14.4, 微信版本：8.0.8.37  导出的网页文件 模板右上角没有查找搜索功能呀？

**Comment by BlueMatthew** [comment]
> iTunes版本：12.11.3.17, iOS版本：14.4, 微信版本：8.0.8.37 导出的网页文件 模板右上角没有查找搜索功能呀？

菜单“选项”中要选中一下，默认是不带这个搜索过滤功能的。

**Comment by yemelody** [comment]
请问下那些声称可以恢复删除的聊天记录的功能 能实现吗

**Comment by BlueMatthew** [comment]
> 请问下那些声称可以恢复删除的聊天记录的功能 能实现吗

我觉得应该不行 需要看sqlite方面的技术了
