### ISSUE TITLE
请问支持 iOS 15.0 的备份么？

### ISSUE THREAD

**Issue by sbilly** [BlueMatthew/WechatExporter#35]
请问支持 iOS 15.0 的备份么？

macOS 11.6 + iOS 15.0 打开备份目录的时候提示无法解析

没有找到带调试信息的版本

**Comment by BlueMatthew** [comment]
我测试一下

**Comment by sbilly** [comment]
不是系统默认的目录，是一个软连接

`
ln -s /somewhere /Users/billy/Library/Application\ Support/MobileSync/Backup
`

**Comment by BlueMatthew** [comment]
那你试试直接选择backup下一级的那个目录试试

**Comment by BlueMatthew** [comment]
> 不是系统默认的目录，是一个软连接
> 
> `ln -s /somewhere /Users/billy/Library/Application\ Support/MobileSync/Backup`

我后面也测试一下软连接的目录

**Comment by sbilly** [comment]
> 那你试试直接选择backup下一级的那个目录试试

Backup 目录和 Backup 目录下的那个 hash 一样的目录我都试过，都是提示无法解析

**Comment by BlueMatthew** [comment]
> > 那你试试直接选择backup下一级的那个目录试试
> 
> Backup 目录和 Backup 目录下的那个 hash 一样的目录我都试过，都是提示无法解析

能截屏看一下你备份出来的目录结构是怎么样的吗？/somewhere的就可以，类似下面这样的
<img width="693" alt="folderstructure" src="https://user-images.githubusercontent.com/37573096/135409544-c685d0e2-b088-435a-a44f-65b5f4c82950.png">

另外，既然你备份在/somewhere这个目录下面的，那有直接选择“/somewhere”这个目录来解析过吗？

**Comment by BlueMatthew** [comment]
> > 那你试试直接选择backup下一级的那个目录试试
> 
> Backup 目录和 Backup 目录下的那个 hash 一样的目录我都试过，都是提示无法解析

貌似重现了，我调试一下

**Comment by BlueMatthew** [comment]
你是通过那个"..."的按钮选择目录的吗，今天调试的时候发现选择目录的时候有一个bug，导致使用的目录不是选择的，会出现解析错误，如果是这样的情况，你试试附件的版本，看是否解决问题了

[v1.9.0.1_x64_macos.zip](https://github.com/BlueMatthew/WechatExporter/files/7323006/v1.9.0.1_x64_macos.zip)

**Comment by hyf168** [comment]
使用你的邮箱，给我邮箱发个，我们沟通一下，应该是小问题

**Comment by BlueMatthew** [comment]
关闭本issue，如还有问题，请新开。
