### ISSUE TITLE
HTTP Status: 400和failed DL

### ISSUE THREAD

**Issue by Redcxx** [BlueMatthew/WechatExporter#36]
你好，软件很好用，但是log有时会报错，如图：
![image](https://user-images.githubusercontent.com/39546701/135749765-3e22bd5c-2f4b-4d9e-954c-6be1fa2ffa31.png)

这是短时间内出错的，是网络波动的缘故吗？会导致某些记录的图片不可用吗？

另外能问一下emoji.qpic.cn和vweixinf.tc.qq.com是哪里找到的接口吗，纯属好奇。

**Comment by Redcxx** [comment]
![image](https://user-images.githubusercontent.com/39546701/135751835-0e9c97fd-b1db-4daa-a93a-a371431dbd46.png)
在98%这卡一早上了，是东西太多了吗

**Comment by BlueMatthew** [comment]
> 你好，软件很好用，但是log有时会报错，如图： ![image](https://user-images.githubusercontent.com/39546701/135749765-3e22bd5c-2f4b-4d9e-954c-6be1fa2ffa31.png)
> 
> 这是短时间内出错的，是网络波动的缘故吗？会导致某些记录的图片不可用吗？
> 
> 另外能问一下emoji.qpic.cn和vweixinf.tc.qq.com是哪里找到的接口吗，纯属好奇。

你可以把url拷贝出来，直接浏览器打开，看看是否也出错。如果浏览器能成功打开，那可能是当时网络波动，或者工具中存在什么bug。再重新导出一遍试试呢。

这些链接都是微信的数据里面的哦

**Comment by BlueMatthew** [comment]
> ![image](https://user-images.githubusercontent.com/39546701/135751835-0e9c97fd-b1db-4daa-a93a-a371431dbd46.png) 在98%这卡一早上了，是东西太多了吗

看到日志显示有4w多个文件需要下载，时间应该需要一些，不过也不应该要一上午。不确定是不是存在存在bug了，你再试一遍，看看是不是还是这样，如果还是这样，我出一个带更多日志的让你帮忙导出一些调试信息看看哪里出错了。

**Comment by Redcxx** [comment]
一上午是有点夸大了，现在也就2-3小时吧，我再等等吧！谢谢

**Comment by BlueMatthew** [comment]
> 一上午是有点夸大了，现在也就2-3小时吧，我再等等吧！谢谢

那大概率也是死锁了，你可以再等等看，汗，也可以再导出一遍试试。 我整一个带日志的版本吧。

**Comment by Redcxx** [comment]
![image](https://user-images.githubusercontent.com/39546701/135755962-235d8be3-3234-4c7b-8d27-f7f33511f023.png)

直接打开失败的链接没问题。
log断断续续有点更新吧，不过主要是失败的信息，不过4万多个图片要下载到什么时候还真不知道，有进度条就好了。

**Comment by BlueMatthew** [comment]
> ![image](https://user-images.githubusercontent.com/39546701/135755962-235d8be3-3234-4c7b-8d27-f7f33511f023.png)
> 
> 直接打开失败的链接没问题。 log断断续续有点更新吧，不过主要是失败的信息，不过4万多个图片要下载到什么时候还真不知道，有进度条就好了。

链接可以直接浏览器里打开没有问题的。

如果还有日志出来，那说明没有死锁。。。你再等等吧，内部好像是3个线程在下载，按理不需要这么久 。。

**Comment by Redcxx** [comment]
后来等了4个多小时还是取消了，请问有那种只储存链接然后以后看的时候再加载的模式吗？
不过没有的话问题也不是很大，我保存为html是因为方便解析看看群友的活跃程度而已，不需要看他们发了什么图片。
谢谢啦

**Comment by BlueMatthew** [comment]
可以 这个功能也合理的 后面我加一下

**Comment by BlueMatthew** [comment]
[v1.9.0.1_x64_win.zip](https://github.com/BlueMatthew/WechatExporter/files/7322941/v1.9.0.1_x64_win.zip)

我把表情下载加了一个控制，在选项菜单中，你试一下，看看卡死的情况是不是解决了。（要先设置一下菜单，默认情况还是下载表情的）。
