### ISSUE TITLE
导出记录不完整，有些好友的聊天记录缺少最近几天的

### ISSUE THREAD

**Issue by et2010** [BlueMatthew/WechatExporter#38]
非常好用的导出软件，谢谢作者！

导出过程中遇到一些问题，使用最新release（1.9.0.1）导出时，发现有些好友的聊天记录缺少最近几天的。大家有遇到这样的问题吗？有没有解决办法呢？谢谢！！

**Comment by BlueMatthew** [comment]
iTunes备份是最新的吗？

**Comment by BlueMatthew** [comment]
> 不知道有没有帮助，有丢失记录现象的好友聊天记录超过了10000条，导出的格式选择的html @BlueMatthew

所有聊天记录数超过10000的都出现这样的情况了吗？

**Comment by zbldsg** [comment]
我也出现了这种情况，19号导出的， 聊天记录只到14号， 但是我看导出的文件夹里的聊天图片有最新的

**Comment by et2010** [comment]
谢谢分享！但是用这种方法还是有显示不全的可能性。

**Comment by BlueMatthew** [comment]
是的，是分页的js有bug，我要看看怎么修复。前端不是那么擅长，我得花点时间 :)

**Comment by BlueMatthew** [comment]
v1.9.0.1的程序包我也更新过了，可以直接下载
