### ISSUE TITLE
请问微信的小表情显示功能可以加上吗?

### ISSUE THREAD

**Issue by zbldsg** [BlueMatthew/WechatExporter#39]
![image](https://user-images.githubusercontent.com/24469929/138247189-963a6c41-2ea9-42e1-beff-9d257490d731.png)
类似这样的, 如果能加入就更好了

再次感谢作者的伟大付出! 感谢感谢!!

**Comment by BlueMatthew** [comment]
可以用版本1.9.0.2试一下

**Comment by zbldsg** [comment]
> 可以用版本1.9.0.2试一下

可以了, 表情图片有了, 再次非常感谢作者伟大付出!!!
