### ISSUE TITLE
解析itunes backup文件失败

### ISSUE THREAD

**Issue by ifnothinghappened** [BlueMatthew/WechatExporter#4]
mac 10.14.6系统
请问可能是什么原因呢？依赖的库没有装正确吗？

**Comment by ifnothinghappened** [comment]
emmm作者大大。 我没怎么学过cpp，安装了一下午的三方库。。之后会考虑把依赖的三方库封装在一起 release吗？

**Comment by BlueMatthew** [comment]
> mac 10.14.6系统
> 请问可能是什么原因呢？依赖的库没有装正确吗？

能看到你的iTunes版本吗？

**Comment by BlueMatthew** [comment]
> emmm作者大大。 我没怎么学过cpp，安装了一下午的三方库。。之后会考虑把依赖的三方库封装在一起 release吗？

不能的mac版本，可能编译出来的文件会不太一样，我可以试着提供一份，但是不确定在你们的电脑上是否还能编译成功。你xcode有的是伐？

**Comment by ifnothinghappened** [comment]
12

> > emmm作者大大。 我没怎么学过cpp，安装了一下午的三方库。。之后会考虑把依赖的三方库封装在一起 release吗？
> 
> 不能的mac版本，可能编译出来的文件会不太一样，我可以试着提供一份，但是不确定在你们的电脑上是否还能编译成功。你xcode有的是伐？



> > mac 10.14.6系统
> > 请问可能是什么原因呢？依赖的库没有装正确吗？
> 
> 能看到你的iTunes版本吗？

12.9.5.5 。看了另个issue 这个文件名00008020-00090D3A0A90003A 字数会有问题吗

**Comment by BlueMatthew** [comment]
> 12
> 
> > > emmm作者大大。 我没怎么学过cpp，安装了一下午的三方库。。之后会考虑把依赖的三方库封装在一起 release吗？
> > 
> > 
> > 不能的mac版本，可能编译出来的文件会不太一样，我可以试着提供一份，但是不确定在你们的电脑上是否还能编译成功。你xcode有的是伐？
> 
> > > mac 10.14.6系统
> > > 请问可能是什么原因呢？依赖的库没有装正确吗？
> > 
> > 
> > 能看到你的iTunes版本吗？
> 
> 12.9.5.5 。看了另个issue 这个文件名00008020-00090D3A0A90003A 字数会有问题吗

貌似我有个mac majove+itunes 12.9.5.5，我先测试一下。

**Comment by ifnothinghappened** [comment]
backup里除了文件夹有这4个文件。然后访问的时候我给它开了完全磁盘访问权限
Info.plist
Manifest.db
Manifest.plist
Status.plist

**Comment by BlueMatthew** [comment]
> backup里除了文件夹有这4个文件。然后访问的时候我给它开了完全磁盘访问权限
> Info.plist
> Manifest.db
> Manifest.plist
> Status.plist

所以你的备份目录 /Users/[user name]/Library/Application Support/MobileSync/Backup下面的子目录名是： 00008020-00090D3A0A90003A 
然后 00008020-00090D3A0A90003A  目录下存在这四个文件：
Info.plist
Manifest.db
Manifest.plist
Status.plist

是这样吧？

**Comment by BlueMatthew** [comment]
我测试了一下iTunes 12.9.5.5备份出来的文件解析，看上去能成功导出的。你运行的是最新的1.7.6的版本吗？iTunes的备份目录是默认就选好的吧？

**Comment by ifnothinghappened** [comment]
> 我测试了一下iTunes 12.9.5.5备份出来的文件解析，看上去能成功导出的。你运行的是最新的1.7.6的版本吗？iTunes的备份目录是默认就选好的吧？

作者大大，突然发现。我下载的好像是1.7.2 就是你md文档里那个。。难怪。。下载了新的，目前能读取了！牛

**Comment by BlueMatthew** [comment]
> > 我测试了一下iTunes 12.9.5.5备份出来的文件解析，看上去能成功导出的。你运行的是最新的1.7.6的版本吗？iTunes的备份目录是默认就选好的吧？
> 
> 作者大大，�突然发现。我下载的好像是1.7.2 就是你md文档里那个。。难怪。。下载了新的，目前能读取了！牛

那不错 :)，有问题可以再发在这里。

**Comment by BlueMatthew** [comment]
> > 我测试了一下iTunes 12.9.5.5备份出来的文件解析，看上去能成功导出的。你运行的是最新的1.7.6的版本吗？iTunes的备份目录是默认就选好的吧？
> 
> 作者大大，�突然发现。我下载的好像是1.7.2 就是你md文档里那个。。难怪。。下载了新的，目前能读取了！牛

看来我还需要清理一下项目中的各种二进制链接 :)

**Comment by ifnothinghappened** [comment]
> > > 我测试了一下iTunes 12.9.5.5备份出来的文件解析，看上去能成功导出的。你运行的是最新的1.7.6的版本吗？iTunes的备份目录是默认就选好的吧？
> > 
> > 
> > 作者大大，�突然发现。我下载的好像是1.7.2 就是你md文档里那个。。难怪。。下载了新的，目前能读取了！牛
> 
> 那不错 :)，有问题可以再发在这里。

我再测试一波win的。 
另外有个功能个人感觉挺实用的。 就是导出的时候能选择导出具体几个对话。 因为好友实在太多了。。其实想存档的就几个。。 hh 只是我感觉比较使用

**Comment by BlueMatthew** [comment]
> > > > 我测试了一下iTunes 12.9.5.5备份出来的文件解析，看上去能成功导出的。你运行的是最新的1.7.6的版本吗？iTunes的备份目录是默认就选好的吧？
> > > 
> > > 
> > > 作者大大，�突然发现。我下载的好像是1.7.2 就是你md文档里那个。。难怪。。下载了新的，目前能读取了！牛
> > 
> > 
> > 那不错 :)，有问题可以再发在这里。
> 
> 我再测试一波win的。
> 另外有个功能个人感觉挺实用的。 就是导出的时候能选择导出具体几个对话。 因为好友实在太多了。。其实想存档的就几个。。 hh 只是我感觉比较使用

你如果有windows，那可以用windows的版本，win版本已经实现了这样的功能，mac版本因为懒还没有做，汗

**Comment by ifnothinghappened** [comment]
> > > > > 我测试了一下iTunes 12.9.5.5备份出来的文件解析，看上去能成功导出的。你运行的是最新的1.7.6的版本吗？iTunes的备份目录是默认就选好的吧？
> > > > 
> > > > 
> > > > 作者大大，�突然发现。我下载的好像是1.7.2 就是你md文档里那个。。难怪。。下载了新的，目前能读取了！牛
> > > 
> > > 
> > > 那不错 :)，有问题可以再发在这里。
> > 
> > 
> > 我再测试一波win的。
> > 另外有个功能个人感觉挺实用的。 就是导出的时候能选择导出具体几个对话。 因为好友实在太多了。。其实想存档的就几个。。 hh 只是我感觉比较使用
> 
> 你如果有windows，那可以用windows的版本，win版本已经实现了这样的功能，mac版本因为懒还没有做，汗

另外好像mac下文件导出， 比如pdf这些 只能导出非常少的一部分。。这个原因是啥呢

**Comment by BlueMatthew** [comment]
> > > > > > 我测试了一下iTunes 12.9.5.5备份出来的文件解析，看上去能成功导出的。你运行的是最新的1.7.6的版本吗？iTunes的备份目录是默认就选好的吧？
> > > > > 
> > > > > 
> > > > > 作者大大，�突然发现。我下载的好像是1.7.2 就是你md文档里那个。。难怪。。下载了新的，目前能读取了！牛
> > > > 
> > > > 
> > > > 那不错 :)，有问题可以再发在这里。
> > > 
> > > 
> > > 我再测试一波win的。
> > > 另外有个功能个人感觉挺实用的。 就是导出的时候能选择导出具体几个对话。 因为好友实在太多了。。其实想存档的就几个。。 hh 只是我感觉比较使用
> > 
> > 
> > 你如果有windows，那可以用windows的版本，win版本已经实现了这样的功能，mac版本因为懒还没有做，汗
> 
> 另外好像mac下文件导出， 比如pdf这些 只能导出非常少的一部分。。这个原因是啥呢

是发送的pdf文件吗？一部分导出来了，一部分没有导出来？没有导出来的是显示【文件】？

**Comment by BlueMatthew** [comment]
> > > > > > 我测试了一下iTunes 12.9.5.5备份出来的文件解析，看上去能成功导出的。你运行的是最新的1.7.6的版本吗？iTunes的备份目录是默认就选好的吧？
> > > > > 
> > > > > 
> > > > > 作者大大，�突然发现。我下载的好像是1.7.2 就是你md文档里那个。。难怪。。下载了新的，目前能读取了！牛
> > > > 
> > > > 
> > > > 那不错 :)，有问题可以再发在这里。
> > > 
> > > 
> > > 我再测试一波win的。
> > > 另外有个功能个人感觉挺实用的。 就是导出的时候能选择导出具体几个对话。 因为好友实在太多了。。其实想存档的就几个。。 hh 只是我感觉比较使用
> > 
> > 
> > 你如果有windows，那可以用windows的版本，win版本已经实现了这样的功能，mac版本因为懒还没有做，汗
> 
> 另外好像mac下文件导出， 比如pdf这些 只能导出非常少的一部分。。这个原因是啥呢

看了一下代码，确实发送的文件没有导出来，转发的消息中的文件倒是导出了，已经修复，会包含在下一个版本。

**Comment by BlueMatthew** [comment]
新版本已经好了，你可以试试，发送的文件已经导出来了。另外，mac版本也支持微信账号的聊天群的选择了。

**Comment by BlueMatthew** [comment]
列的问题已解决
