### ISSUE TITLE
导出的聊天记录,  我发给对方的图片都可以点击放大, 但是对方发给我的图片, 只有一个缩略图, 点击放大不起作用也

### ISSUE THREAD

**Issue by zbldsg** [BlueMatthew/WechatExporter#40]
我手机上查看图片是正常可以点开放大的

**Comment by zbldsg** [comment]
> 好的 我用你的方法重现一下

感谢作者付出, 还想请问下, 这个问题 我刚试了下1.9.5.6版本还是不大行呢?

**Comment by zbldsg** [comment]
> 你给我发个邮件给我，让我知道你的邮箱： [matthewreg@hotmail.com](mailto:matthewreg@hotmail.com)

已发

**Comment by BlueMatthew** [comment]
v1.9.5.8修复

**Comment by zbldsg** [comment]
> v1.9.5.8修复

非常感谢, 作者万岁
