### ISSUE TITLE
请问如何获得解密后的原始数据文件

### ISSUE THREAD

**Issue by flyboss** [BlueMatthew/WechatExporter#42]
您好，我从安卓的一些教程中看到，可以把db文件通过sqlcipher解密后查询。但是我在该项目中没有找到“解密后的数据文件”，似乎程序直接将其转换成了html文件。

我的需求是要查看之前的一些视频号和小程序分享链接，但是我发现现在解析出来的链接都不能用了，所以我想直接去检查原始的数据，当然作者大大要是有时间修分享链接的问题，那更好了，万分感谢！

**Comment by flyboss** [comment]
明白了，谢谢。

我看Android聊天记录中小程序、视频号似乎都是xml格式的数据，iphone中应该也是这样吧？请问我从哪里能看到这样原始的数据文件呢？

**Comment by BlueMatthew** [comment]
你留个邮箱 回头我发你一份样例

**Comment by ichengzi** [comment]
同样希望保留一份解密后的db文件，方便SQL方式针对性提取

**Comment by flyboss** [comment]
谢谢您，我的邮箱是 flyboss@126.com
