### ISSUE TITLE
release的编译好的文件在macos上解压缩后无法使用

### ISSUE THREAD

**Issue by xiaoqiao** [BlueMatthew/WechatExporter#47]
MacOS Monterey
version 12.0.1
MacBook Pro 16inch 2021
chip Apple M1 Pro

keka,和系统自带的都解压了：
或者是提示文件损坏，或者是：

![image](https://user-images.githubusercontent.com/2181709/144983759-e5211e32-dff8-4a76-ba69-2c7d50fe524a.png)

**Comment by BlueMatthew** [comment]
请点桌面左上角的苹果图标菜单：系统偏好设置\安全性与隐私，应该有提示允许"WechatExporter"运行的提示，点击[仍要打开]按钮，应该就可以了
<img width="676" alt="截屏2021-12-08 上午11 28 58" src="https://user-images.githubusercontent.com/37573096/145144225-594e178b-11ed-42d6-bf5d-dba2bcfca87a.png">

**Comment by flute** [comment]
Email已收到，谢谢！

**Comment by xiaoqiao** [comment]
> 请点桌面左上角的苹果图标菜单：系统偏好设置\安全性与隐私，应该有提示允许"WechatExporter"运行的提示，点击[仍要打开]按钮，应该就可以了 <img alt="截屏2021-12-08 上午11 28 58" width="676" src="https://user-images.githubusercontent.com/37573096/145144225-594e178b-11ed-42d6-bf5d-dba2bcfca87a.png">

可以了 ，谢谢
