### ISSUE TITLE
如何直接读取sqlite数据库

### ISSUE THREAD

**Issue by xiaoqiao** [BlueMatthew/WechatExporter#52]
你好，非常感谢开源这个很有用的project，
我想对聊天记录做一些统计和处理，但是现在只能通过导出text然后再自己写入数据库的方式来进行，免不了有一些格式的问题。
（现在导出txt文件，不是完全的一行一条纪录，偶尔出现下一条纪录和这一条连在一起的情况）

所以有没有可能能给出一个直接导出sqlite数据库的选项？
谢谢~

**Comment by BlueMatthew** [comment]
> 你好，非常感谢开源这个很有用的project， 我想对聊天记录做一些统计和处理，但是现在只能通过导出text然后再自己写入数据库的方式来进行，免不了有一些格式的问题。 （现在导出txt文件，不是完全的一行一条纪录，偶尔出现下一条纪录和这一条连在一起的情况）

能给个例子看看吗，可能是存在bug，按理是不同消息不应该在一样的。

> 
> 所以有没有可能能给出一个直接导出sqlite数据库的选项？ 谢谢~

如果你了解微信的数据结构，你可以直接用iTunesBackup这个程序来导出微信的原始数据，进行查询，不过数据比较原始，需要做一些关联。

https://github.com/BlueMatthew/iTunesBackup

**Comment by zhoubeichen20** [comment]
楼主厉害！行动力这么强！关于 微信的数据结构，有比较全，权威一点的文章参考嘛~ 
不希望做伸手党，但是有个时候谷歌也真的比较难找到合适的内容~

**Comment by BlueMatthew** [comment]
> 楼主厉害！行动力这么强！关于 微信的数据结构，有比较全，权威一点的文章参考嘛~ 不希望做伸手党，但是有个时候谷歌也真的比较难找到合适的内容~

其实也就google上通过搜索“微信 逆向”之类的关键词找到的那些文章，结合这些文章加上导出微信文件之后，自己的一些分析和猜测 :)

**Comment by zhoubeichen20** [comment]
嗯 好的，谢谢，这么及时的回复，感恩！
