### ISSUE TITLE
mac版本没有导出txt功能，请问有办法直接导出txt吗

### ISSUE THREAD

**Issue by zlsq** [BlueMatthew/WechatExporter#58]
如题

**Comment by Aqumik** [comment]
格式 选择 文本模式

**Comment by zhoubeichen20** [comment]
Mac 版本可以导出啊。然后你可能会觉得这个有用： wemory.co

**Comment by BlueMatthew** [comment]
可以通过菜单中的格式进行修改输出的格式：

![image](https://user-images.githubusercontent.com/37573096/148161337-5cd03808-28e5-429e-b3d2-79249e81c98f.png)

**Comment by BlueMatthew** [comment]
> Mac 版本可以导出啊。然后你可能会觉得这个有用： [wemory.co](wemory.co)

云服务不错，付费的用户多伐？

**Comment by BlueMatthew** [comment]
Not issue and close it.
