### ISSUE TITLE
No more txt chat log exporting?

### ISSUE THREAD

**Issue by bylmy** [BlueMatthew/WechatExporter#6]
Is that no more txt version export? Ver1.5.0 did that work. HTML files too large to transfer or copy. Any idea?

**Comment by BlueMatthew** [comment]
> Is that no more txt version export? Ver1.5.0 did that work. HTML files too large to transfer or copy. Any idea?

No, I didn't implement that after migration. But you can simply the templates to make a text-only version. May find the templates in the res/templates folder.

**Comment by BlueMatthew** [comment]
> > Is that no more txt version export? Ver1.5.0 did that work. HTML files too large to transfer or copy. Any idea?
> 
> No, I didn't implement that after migration. But you can simply the templates to make a text-only version. May find the templates in the res/templates folder.

I have tested this way and seems there is something wrong. I will update it to support plain text mode.

**Comment by BlueMatthew** [comment]
I have maken the templates for text mode and fixed the bug of the program, you may use the latest version to try it after replacing the text templates on "res" folder(copy files of templates_txt into templates folder).

Any issue, pls let me know.

**Comment by bylmy** [comment]
Thanks Matthew. 

Tried v1.7.9 as your aboved Intro. guide, which by relplaced with text templates on "res" folder, then I got an unformated html file but not txt file. I aslo selected "文本" under "格式" menu although there is no ticked sign after click. If I missing any steps? 

However by v1.5.0, I can get formatted txt file exported by filted out pics, videos, etc, that what I really want. Actually there is no contacts selection by this version and have to export all contacts chatting scripts.

**Comment by BlueMatthew** [comment]
Ohhh... that html should be plain-text contents but I did not change the file name from .html to .txt. And the menu of "格式" hasn't be implemented yet[Shy].

As for that v1.5.0 which can export txt content, you mean WechatExporter-iOS, right? I will implement the UI control for txt mode in the next version and then pls try it again.

**Comment by BlueMatthew** [comment]
You may try 1.7.10 for text mode. on windows version, choose text mode from menu: 格式/文本

Any issue, please feel free to let me know.

**Comment by bylmy** [comment]
Nice job Matthew! Just tried 1.7.10 that is working smooth, both HTML and TXT mode are running perfect. Thanks a lot.

**Comment by BlueMatthew** [comment]
Just find a big issue that audio won't be exported on windows when the folder has unicode characters. If you needs html files, pls export again.
