### ISSUE TITLE
华为有方法导嘛

### ISSUE THREAD

**Issue by lixuedong1024** [BlueMatthew/WechatExporter#60]

**Comment by BlueMatthew** [comment]
Android的数据库都是加密的，技术上是有办法解析的，网络上也有一些讨论的文章，不过这个比较灰色。所以我的建议还是去找一个iOS设备，譬如iPad之类的，把聊天记录迁移到iOS设备上(印象中微信目前应该可以设备到设备直接迁移了)，然后再利用这个工具到出来 :)

**Comment by lixuedong1024** [comment]
好的  多谢指导
