### ISSUE TITLE
提几个优化建议，希望能在后续版本中逐步采纳

### ISSUE THREAD

**Issue by GithubGaoYang** [BlueMatthew/WechatExporter#62]
1. 建议增加时间段选择功能
> 可参考微信“恢复聊天记录至手机-更多选项”的设计

2. 建议增加名称的搜索功能
> 目前聊天记录过多，在期望只备份某几个聊天的时候不容易查找，希望可以通过搜索提高易用性（哪怕只是高亮一下搜索关键词也可）

3. 建议修改名称排序规则，
> 目前似乎是通过Unicode编码默认排序的，对中文的排序不友好，建议处理下（查了下资料，好像是可以通过设置 locale=zh_CN 实现）
举例（递增排序）：
["右手", "重要", "重庆", "边城"]
当前排序：["右手", "边城", "重要", "重庆"]
期望排序：["边城", "重庆", "右手", "重要"]

4. 建议增加时间导航功能
> 可参考[微信聊天记录导出](http://wxbackup.imxfd.com/)这个工具，看到之前有类似issue，但尚在讨论中，如果您愿意增加此功能，可以搞个 todo list，以免提出一些计划内的issue

5. 建议有群备注时，群名与群备注可以同时导出
> 哪怕只是在群备注后加个括号展示一下呢~

6. 增量导出时，index.html 会被重写
> 举个例子：
昨天导出了 abc 三个好友的聊天记录，然后就把备份文件删了，今天新增了bcd三个好友的数据，再次备份导出，index.html 中目前只有bcd的索引，期望应该是abcd

7. 增量导出时，每次都要重新下载文件吗？
> 因为同一个群聊，尝试多次导出，发现每次都会有`Waiting for tasks: xx downloads`信息
目前不清楚下载的是什么文件，如果是图片表情等资源，是不是可以判断一下，本地已经存在了就不要再下载了？
重复下载会比较费时间

8. iTunes 备份文件的时间显示有误（早了 8 小时）
> 应该是时区问题

提的比较多，希望大佬可以酌情采纳，毕竟，这是目前最好用的导出工具了~

**Comment by BlueMatthew** [comment]
非常感谢 回头我整理到 todo list里面 ：）


Best regards,
Matthew


在 2022年1月7日，15:28，GithubGaoYang ***@***.***> 写道：

﻿

  1.  建议增加时间段选择功能

可参考微信“恢复聊天记录至手机-更多选项”的设计

  1.  建议增加名称的搜索功能

目前聊天记录过多，在期望只备份某几个聊天的时候不容易查找，希望可以通过搜索提高易用性（哪怕只是高亮一下搜索关键词也可）

  1.  建议修改名称排序规则，

目前似乎是通过Unicode编码默认排序的，对中文的排序不友好，建议处理下（查了下资料，好像是可以通过设置 locale=zh_CN 实现）
举例（递增排序）：
["右手", "重要", "重庆", "边城"]
当前排序：["右手", "边城", "重要", "重庆"]
期望排序：["边城", "重庆", "右手", "重要"]

  1.  建议增加时间导航功能

可参考微信聊天记录导出<https://apac01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwxbackup.imxfd.com%2F&data=04%7C01%7C%7C06d2d120d03e4e236b7608d9d1af41d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771372928648094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6aPzhf9oQeBsg20D%2BV4OpOP4I%2FMtI7XiGnkhQUXBY3E%3D&reserved=0>这个工具，看到之前有类似issue，但尚在讨论中，如果您愿意增加此功能，可以搞个 todo list，以免提出一些计划内的issue

  1.  建议有群备注时，群名与群备注可以同时导出

哪怕只是在群备注后加个括号展示一下呢~

  1.  增量导出时，index.html 会被重写

举个例子：
昨天导出了 abc 三个好友的聊天记录，然后就把备份文件删了，今天新增了bcd三个好友的数据，再次备份导出，index.html 中目前只有bcd的索引，期望应该是abcd

  1.  增量导出时，每次都要重新下载文件吗？

因为同一个群聊，尝试多次导出，发现每次都会有Waiting for tasks: xx downloads信息
目前不清楚下载的是什么文件，如果是图片表情等资源，是不是可以判断一下，本地已经存在了就不要再下载了？
重复下载会比较费时间

  1.  iTunes 备份文件的时间显示有误（早了 8 小时）

应该是时区问题

提的比较多，希望大佬可以酌情采纳，毕竟，这是目前最好用的导出工具了~

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBlueMatthew%2FWechatExporter%2Fissues%2F62&data=04%7C01%7C%7C06d2d120d03e4e236b7608d9d1af41d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771372928648094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=poWxJS22ceAJtc408Gv5L9UrPuJ6SvVGmbtzGW2VStE%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI6VD2HDBALEOPWI4GDRQF3UU2IYVANCNFSM5LOFW4FA&data=04%7C01%7C%7C06d2d120d03e4e236b7608d9d1af41d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771372928648094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TDqCzOH5zMPANYt4uRtBZ4Bg%2BHk5STg9mwfHEx4pjOQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C06d2d120d03e4e236b7608d9d1af41d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771372928804300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lRwlbmyKrCUfjqxXgldkvIdOzGRl16laUNvzurjACaY%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C06d2d120d03e4e236b7608d9d1af41d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771372928804300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fG76SuYVnfA3yNdeKUjPZa9LGw3vgD7rzYMLyjcpD4M%3D&reserved=0>.

**Comment by BlueMatthew** [comment]
都已经记录在wiki中： https://github.com/BlueMatthew/WechatExporter/wiki
后面会陆续更新。

关闭 issue
