### ISSUE TITLE
备份时失败了 然后发现C盘满了

### ISSUE THREAD

**Issue by haotry** [BlueMatthew/WechatExporter#63]
然后发现C盘满了 删除了40多个G的备份文件... 
备份整个手机代价太大了点

**Comment by haotry** [comment]
使用命令 mklink/j "C:\Users\你的用户\AppData\Roaming\Apple Computer\MobileSync" "新的路径"

**Comment by BlueMatthew** [comment]
这种方式也可以吧 我之前是用junction转移到d盘的

最近在做一个定制化备份 来替代itunes备份 这种方式只备份微信数据 会对磁盘压力小一点 不过还没有完成

**Comment by BlueMatthew** [comment]
本功能已经在处理中，wiki的 todo list也已经记录，关闭本issue
