### ISSUE TITLE
多媒体信息的导出

### ISSUE THREAD

**Issue by hardyho** [BlueMatthew/WechatExporter#64]
是否可以在导出为txt时添加语音时长信息（由于语音本身会缓存到本地，应该很好获取），另外是否有接口获得通话时长？
另，在导出来自其他app的分享链接至txt时存在末尾不换行的bug，并且信息也较简单，是否有可能增加 [分享自] 的tag。

**Comment by BlueMatthew** [comment]
应该修改模版就可以 会在下一个版本修复


Best regards,
Matthew


在 2022年1月11日，20:16，He Haodi ***@***.***> 写道：

﻿

是否可以在导出为txt时添加语音时长信息（由于语音本身会缓存到本地，应该很好获取），另外是否有接口获得通话时长？
另，在导出来自其他app的分享链接至txt时存在末尾不换行的bug，并且信息也较简单，是否有可能增加 [分享自] 的tag。

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBlueMatthew%2FWechatExporter%2Fissues%2F64&data=04%7C01%7C%7C504e35fcfeb14a8a0c3408d9d4fc2b1e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775001787525007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vSvemjhZKNieLABHrmfYwrfxbFNHFlNi9BIMVI6Acg0%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI6VD2CXMBH6F7O25Y7W7OLUVQNRBANCNFSM5LWE5QEA&data=04%7C01%7C%7C504e35fcfeb14a8a0c3408d9d4fc2b1e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775001787525007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XWU9VXjv7NoWB4xLC3kylJVnwQMlPyuprg1jmHpAIBY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C504e35fcfeb14a8a0c3408d9d4fc2b1e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775001787525007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eEpHAUnCrWuGBHuiE58PTGpKOZxK8vMCOAjt6zCuYzY%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C504e35fcfeb14a8a0c3408d9d4fc2b1e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775001787525007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4OoXNn0K6PnOK%2BnRNvEDPV4pLMrT9g0V5aoenpjheYs%3D&reserved=0>.

**Comment by BlueMatthew** [comment]
[v1.9.2.1.zip](https://github.com/BlueMatthew/WechatExporter/files/7871263/v1.9.2.1.zip)

导出为text格式的语音时长确实有bug，已经修正了，分享缺少换行的问题也修复。可以试试附件的程序

**Comment by BlueMatthew** [comment]
问题已经解决，关闭issue，如果还有其它问题，请再开issue
