### ISSUE TITLE
部分私信里的部分语音或者表情丢失

### ISSUE THREAD

**Issue by jarywong** [BlueMatthew/WechatExporter#65]
部分私信里的部分语音或者表情丢失，手机里语音是没有问题，但是导出的聊天记录里，表现如下。
- 对方的显示为【0:00 / 0:00】，并且自己也是【0:00 / 0:00】
- 自己的显示为【[语音 4193.000000"]】

表情的话，双方都显示【[表情]】，主要是自定义表情和猜拳、摇色子一类的。

不知道是只有自己才有这个问题还是大家也有遇到过这个问题。

**Comment by BlueMatthew** [comment]
语音部分 我回头加一个日志 你到时候再看看是否有更多错误信息
表情的话 中括号内部是具体的表情标签吗？我之前转的 应该还是没有全部包含进去的 不知道是不是这部分


Best regards,
Matthew


在 2022年1月12日，18:21，jarywong ***@***.***> 写道：

﻿

部分私信里的部分语音或者表情丢失，手机里语音是没有问题，但是导出的聊天记录里，表现如下。

  *   对方的显示为【0:00 / 0:00】，并且自己也是【0:00 / 0:00】
  *   自己的显示为【[语音 4193.000000"]】

表情的话，双方都显示【[表情]】

不知道是只有自己才有这个问题还是大家也有遇到过这个问题。

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBlueMatthew%2FWechatExporter%2Fissues%2F65&data=04%7C01%7C%7C91d50a944a1e4a49709308d9d5b54c4b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775796918143893%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Fh98LlLYlsA4AT%2F2kryt90s%2B%2B6S3AiI41lJ1Q6q7knM%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI6VD2BGMPH3R26K4SZZRD3UVVI2TANCNFSM5LYSSMQA&data=04%7C01%7C%7C91d50a944a1e4a49709308d9d5b54c4b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775796918143893%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SSA5dZFst9y6ONxPte4yTAHZ0evDMXosB2DaIOcrilA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C91d50a944a1e4a49709308d9d5b54c4b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775796918143893%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p%2BC%2Bc80DzXNCmioc3z5%2Bnen9ZBORoksj4Bf6aQVSHLI%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C91d50a944a1e4a49709308d9d5b54c4b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637775796918143893%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VsrVXdOGZasuwLplC1ldv36jLSzyMEXlfEX6xjMNpZk%3D&reserved=0>.

**Comment by jarywong** [comment]
好的，谢谢，语音还是希望能留下来的，刚刚看了一下日志，里面确实没有这部分的错误信息、
表情的话就是显示【[表情]】，不过表情没有问题也不是很大。

**Comment by BlueMatthew** [comment]
[v1.9.2.0.zip](https://github.com/BlueMatthew/WechatExporter/files/7870450/v1.9.2.0.zip)

你可以用这个版本，在菜单:文件\输出详细日志打勾，再看看是否有语音转换的错误。

表情是有可能的，目前只是处理了标准的120个左右表情，回头我再看看是否能继续增加。

**Comment by jarywong** [comment]
好的谢谢，我看看

**Comment by jarywong** [comment]
- 自己的显示为【[语音 4193.000000"]】：出现了下面的错误，是不是可能我的备份文件有问题？
```
22:15:20: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\c57f28050fc0ada465dc517251a5c1eae56b7***\52\528707772de8494d14bca557a4fe63d8a24b93a5: ig���ǧ�
Documents/9e4bb36e3823308109e9399ef5f694ce\Audio\d150e3b35284b56075c6d4c2cb562ae8\372.aud
22:15:20: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\c57f28050fc0ada465dc517251a5c1eae56b7***\4a\4a793fda1fcb128c41a8c0c8f2a9d87cdd5a554a: �<���Ƿ�
Documents/9e4bb36e3823308109e9399ef5f694ce\Audio\d150e3b35284b56075c6d4c2cb562ae8\374.aud
22:15:20: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\c57f28050fc0ada465dc517251a5c1eae56b7***\7e\7e792710df6939f2ee202cd6e45fac23b90f253b: ������
Documents/9e4bb36e3823308109e9399ef5f694ce\Audio\d150e3b35284b56075c6d4c2cb562ae8\2.aud
22:15:21: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\c57f28050fc0ada465dc517251a5c1eae56b7***\ed\edac4da2739eeb79919d4bd082818fa08c7daaef: �`&���%�
Documents/9e4bb36e3823308109e9399ef5f694ce\Audio\d150e3b35284b56075c6d4c2cb562ae8\5.aud
22:15:21: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\c57f28050fc0ada465dc517251a5c1eae56b7***\30\302fa639df8743dc0a0ad2dea88c5c07aa7eae7e: �M[�P�5�
Documents/9e4bb36e3823308109e9399ef5f694ce\Audio\d150e3b35284b56075c6d4c2cb562ae8\7.aud
22:15:21: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\c57f28050fc0ada465dc517251a5c1eae56b7***\d6\d6e30a4775da921146620ca528ac17f493fb1b28: {@�����
Documents/9e4bb36e3823308109e9399ef5f694ce\Audio\d150e3b35284b56075c6d4c2cb562ae8\9.aud
22:15:21: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\c57f28050fc0ada465dc517251a5c1eae56b7***\5e\5eb7a6d106480f8ecde134add310d579fbb91ffa: <Bb��.��
Documents/9e4bb36e3823308109e9399ef5f694ce\Audio\d150e3b35284b56075c6d4c2cb562ae8\10.aud
22:15:21: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\c57f28050fc0ada465dc517251a5c1eae56b7***\a0\a03056f6dd80ae3a4cf137931d31181a933944a3: ԫ���u�
Documents/9e4bb36e3823308109e9399ef5f694ce\Audio\d150e3b35284b56075c6d4c2cb562ae8\59.aud
22:18:32: HTTP Status:404
```
- 对方的显示为【0:00 / 0:00】，并且自己也是【0:00 / 0:00】：导出时没出错。我刚刚重新看了一下网页，音频的源文件是没问题的，在外面能播放，但是网页上死活不能正常显示。哦，问题知道了：因为微信里都是语音交互，所以大量的语音导致网页上不能正常加载：
```
***.html:1 
        
       [Intervention]Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
```

**Comment by BlueMatthew** [comment]
我也有少量转换出错的情况，今天看看itunes，文件确实有问题，我回头再仔细看一下手机里的语音是不是正常的，如果手机里正常，那肯定哪个环节出现问题了。

网页里mp3太多的问题，我看看怎么解决，之前确实没有注意到。

**Comment by jarywong** [comment]
昨晚用以前那个wxbackup导出同一个备份，却能正常导出，感觉是不是解析的时候出问题了。
网页里过多语音的可能只能动态加载，保证整个网页的播放器数量保持在一定范围。

**Comment by BlueMatthew** [comment]
我找了一下资料，微信早期的版本是另外一种格式，你看看转失败的是不是都是早期的语音？我因为玩微信比较晚，所以没有遇到这样的数据，汗。

**Comment by jarywong** [comment]
原来是这样啊，没有看有多少聊天记录是这样的，不过上面提到的那个是2015年2月的，另外那几条记录只是我发出去的有问题，我收到的没问题。

**Comment by BlueMatthew** [comment]
我看看怎么来导出这部分语音。

**Comment by jarywong** [comment]
刚刚把所有记录都重新导了一遍，发现虽然也有2017年出错的语音，不过大多数还是集中在2015年，而且不只是自己发出去的，收到的也有出错的，估计可能是那个早期版本的问题

**Comment by BlueMatthew** [comment]
[v1.9.3.1.zip](https://github.com/BlueMatthew/WechatExporter/files/7897263/v1.9.3.1.zip)

你试试这个版本看，微信早期的语音格式也支持导出了，然后html页面中语音的展示也改了方法，只有点击播放的时候才会创建audio组件，避免了你之前遇到的错误。不过我自己测试了一个各种文件很多的的聊天（上万个小文件），发现mp3动态加载的速度比较慢，可能和过多小文件有关，需要后面测试和优化。

另外，视频如果过多，估计也会有类似问题，还没有来得及修改。

**Comment by jarywong** [comment]
我尝试了一下，发现还是不行，另外有部分原来可以的现在也不行了。
日志如下：
```
23:08:58: [DBG] Unknown voice format: 
Documents/9e4bb36e3823308109e9399ef5f69***\Audio\6b7f3c72806c02d65c8edb637a45****\89.aud
23:08:58: [DBG] Unknown voice format: 
Documents/9e4bb36e3823308109e9399ef5f69***\Audio\6b7f3c72806c02d65c8edb637a45****\92.aud
23:08:58: [DBG] Unknown voice format: 
Documents/9e4bb36e3823308109e9399ef5f69***\Audio\6b7f3c72806c02d65c8edb637a45****\93.aud
23:09:28: [DBG] Unknown voice format: 
Documents/9e4bb36e3823308109e9399ef5f69***\Audio\d150e3b35284b56075c6d4c2cb56****\373.aud
```

**Comment by BlueMatthew** [comment]
原来出错的，现在还是导不出来，但是没有报错信息了是吗？

新报错的，原来可以导出？

> 我尝试了一下，发现还是不行，另外有部分原来可以的现在也不行了。 日志如下：
> 
> ```
> 23:08:58: [DBG] Unknown voice format: 
> Documents/9e4bb36e3823308109e9399ef5f69***\Audio\6b7f3c72806c02d65c8edb637a45****\89.aud
> 23:08:58: [DBG] Unknown voice format: 
> Documents/9e4bb36e3823308109e9399ef5f69***\Audio\6b7f3c72806c02d65c8edb637a45****\92.aud
> 23:08:58: [DBG] Unknown voice format: 
> Documents/9e4bb36e3823308109e9399ef5f69***\Audio\6b7f3c72806c02d65c8edb637a45****\93.aud
> 23:09:28: [DBG] Unknown voice format: 
> Documents/9e4bb36e3823308109e9399ef5f69***\Audio\d150e3b35284b56075c6d4c2cb56****\373.aud
> ```

**Comment by jarywong** [comment]
原来的还是出错还是导出不了，但是错误信息跟原来有点区别。
然后那些错误相邻的几条语音原来可以导出，现在也不行了，错误内容一样。

**Comment by BlueMatthew** [comment]
看日志：“Unknown voice format: ”，感觉是存在format为空的语音，导致被我新的处理跳过了。我调整一下代码，再看看能不能行，晚点发给你。

**Comment by BlueMatthew** [comment]
如果你有文本编辑工具，尝试打开 Documents/9e4bb36e3823308109e9399ef5f69***\Audio\6b7f3c72806c02d65c8edb637a45****\89.aud 看看文件开头是不是有 !SILK_V3 这样的文本。

**Comment by BlueMatthew** [comment]
[v1.9.3.2.zip](https://github.com/BlueMatthew/WechatExporter/files/7919853/v1.9.3.2.zip)

试试这个，我把非0的voiceformat都当作silk格式处理了，看看是不是能解决问题。

**Comment by 2894462606** [comment]
希望能解决[表情]的问题，好像是是其它下载的微信表情包都不能导出

**Comment by BlueMatthew** [comment]
我自己只用微信自带的表情 而且是第一屏 汗 其它下载的微信表情包也是微信提供的吗？


Best regards,
Matthew


在 2022年1月23日，23:26，2894462606 ***@***.***> 写道：

﻿

希望能解决[表情]的问题，好像是是其它下载的微信表情包都不能导出

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBlueMatthew%2FWechatExporter%2Fissues%2F65%23issuecomment-1019507622&data=04%7C01%7C%7C47d19a96ca104460783608d9de84c679%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637785484126079124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8GVFPmLJPVkGj0DGSKPOPKKLFGuFjYuovJ56rN2YqFE%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI6VD2BYJZPJYWGIVOO7PYLUXQM3RANCNFSM5LYSSMQA&data=04%7C01%7C%7C47d19a96ca104460783608d9de84c679%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637785484126079124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HsdokkuXUTJ7YcMJvJ0RofABLqTf4Y7vKr%2FFkpuS0rs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C47d19a96ca104460783608d9de84c679%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637785484126079124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rVQir%2FUp59B8flknXmRxkBqmGt%2Bqt%2Fpmcdncx3m8rxM%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C47d19a96ca104460783608d9de84c679%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637785484126079124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NdxdFac4mgqokmHJgSZzrPGHeWAeSstu%2BGfx6JMnlPo%3D&reserved=0>.

**Comment by 2894462606** [comment]
> 我自己只用微信自带的表情 而且是第一屏 汗 其它下载的微信表情包也是微信提供的吗？ Best regards, Matthew 在 2022年1月23日，23:26，2894462606 ***@***.***> 写道： ﻿ 希望能解决[表情]的问题，好像是是其它下载的微信表情包都不能导出 — Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBlueMatthew%2FWechatExporter%2Fissues%2F65%23issuecomment-1019507622&data=04%7C01%7C%7C47d19a96ca104460783608d9de84c679%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637785484126079124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8GVFPmLJPVkGj0DGSKPOPKKLFGuFjYuovJ56rN2YqFE%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI6VD2BYJZPJYWGIVOO7PYLUXQM3RANCNFSM5LYSSMQA&data=04%7C01%7C%7C47d19a96ca104460783608d9de84c679%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637785484126079124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HsdokkuXUTJ7YcMJvJ0RofABLqTf4Y7vKr%2FFkpuS0rs%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C47d19a96ca104460783608d9de84c679%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637785484126079124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rVQir%2FUp59B8flknXmRxkBqmGt%2Bqt%2Fpmcdncx3m8rxM%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C47d19a96ca104460783608d9de84c679%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637785484126079124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NdxdFac4mgqokmHJgSZzrPGHeWAeSstu%2BGfx6JMnlPo%3D&reserved=0>. You are receiving this because you commented.Message ID: ***@***.***>

我指的是其它作者发布在微信上供人下载的表情包，这个不知道有没有办法

**Comment by jarywong** [comment]
昨晚看到邮件了，却忘了回复，我现在下载下来试试。

**Comment by jarywong** [comment]
最新版本的，又跟原来一样啦，还是有部分不行。
另外日志里出错的文件，我导出来了，内容如下，供参考：
HEX
```
0C 69 67 C4 FF F0 C7 A7  FE 7B 06 00 00 00 0C D5
```
ASCII
```
igÄÿðÇ§þ
```

**Comment by BlueMatthew** [comment]
感觉是我弄反了，如果没有设定format，应该当作旧格式处理。重新做了一个版本，希望这次能解决，汗。

这次我会在输出目录建立一个dbg目录，如果出现错误，会把微信的原始消息内容输出出来，是个xml，原始的语音文件也会输出来，是个aud文件，如果format为空转换成功了，会把mp3也输出来，可以直接听听语音是不是对（早期的amr格式转换时的出错处理貌似有点问题，可能会转成错误的mp3，但是没有报错）

[v1.9.3.3.zip](https://github.com/BlueMatthew/WechatExporter/files/7939378/v1.9.3.3.zip)

**Comment by jarywong** [comment]
好了，可以了，我暂时先试了原来有问题的2个人，现在挂机把所有人的都导一遍看看还有没有有问题的

**Comment by jarywong** [comment]
不好意思，发现原来有问题的是好了，可是原来没问题的却变机械音了，时间上跟原来有问题的是一起的，差不多下面这样：
之前
```
对方                我
没问题 
                   未解析
没问题
                   未解析
没问题
```
现在这个版本
```
对方                我
机械音 
                   正常
机械音
                   正常
机械音
```

**Comment by BlueMatthew** [comment]
太好了！

**Comment by BlueMatthew** [comment]
哈 刚看到前面的消息就回复了 空欢喜一场 晚上我把所有的语音xml都导出来吧

**Comment by jarywong** [comment]
我本来也觉得太好了，后来一想，莫非原来好的反而变得不行了？一看，果然不行了。晚上可以导出原始语音的时候，我看看有什么区别吧。按理说同一个时期的，格式上不应该有区别才对

**Comment by BlueMatthew** [comment]
可能相互的微信版本不一样 就会产生区别

**Comment by jarywong** [comment]
哦，这么一说还是有可能的，还有我iOS对方安卓这种可能性

**Comment by jarywong** [comment]
所有聊天记录里面，除去上面说的问题，日志里的语音错误只剩这个了，感觉这个像是真的有问题了。
```
19:39:57: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\***f28050fc0ada465dc517251a5c1eae56b****\f5\****a76d3b933c66240c360d3e64bd897dd4****: 0000000000000000
voiceFormat:*4* Documents/****b36e3823308109e9399ef5f6****\Audio\****eda7762b0fda9f2390a9c37bc2c4\24665.aud
```

**Comment by BlueMatthew** [comment]
> 所有聊天记录里面，除去上面说的问题，日志里的语音错误只剩这个了，感觉这个像是真的有问题了。
> 
> ```
> 19:39:57: [DBG] SILK Error: Wrong Header C:\Users\***\AppData\Roaming\Apple Computer\MobileSync\Backup\***f28050fc0ada465dc517251a5c1eae56b****\f5\****a76d3b933c66240c360d3e64bd897dd4****: 0000000000000000
> voiceFormat:*4* Documents/****b36e3823308109e9399ef5f6****\Audio\****eda7762b0fda9f2390a9c37bc2c4\24665.aud
> ```

少数语音是不对的，我导出自己的聊天记录的时候，也出现了两次，微信里听，也听不到声音。

**Comment by BlueMatthew** [comment]
[v1.9.3.4.zip](https://github.com/BlueMatthew/WechatExporter/files/7954812/v1.9.3.4.zip)

把语音原始数据导出的版本（包括xml，原始的aud文件，以及转换之后的mp3文件，导出文件在输出目录下的dbg子目录），麻烦找一个聊天来导一次，原始的aud文件如果windows上不能支持，可以下载vlc（https://www.videolan.org/vlc/） 播放。

如果可以的话，麻烦找一些不敏感的失败的语音（包括xml和aud），发给我看看   MatthewReg@hotmail.com

![Facepalm](https://user-images.githubusercontent.com/37573096/151468600-5582623a-9103-4f1b-9d9b-37d1af47a064.png)

**Comment by jarywong** [comment]
我看了一下，现在有问题的是
```
#!SILK_V3
```

代码里应该有是这个头部的时候按原来处理的判断吧？
没有这个头的语音现在的版本没问题。

**Comment by jarywong** [comment]
```
那就是没有判断出这个是silk格式的语音，这个消息的xml能发一个出来吗，看看是不是什么数据格式没有判断到。
```
怎么直接编辑我的回复了，我还想着我好像没说这句话。(此处一个苦笑的表情)

消息的xml是这个吗？不过我看了一下，没看出来跟其他的有什么区别。
```
<msg><voicemsg length="3297" endflag="1" cancelflag="0" voicelength="1840" fromusername="wxid_***" isPlayed="1" /></msg>
```

**Comment by BlueMatthew** [comment]
这个xml中缺少一个属性，类似下面：

voiceformat="0"
0是amr格式的。

我这边看到silk格式的应该是
voiceformat="4"

看来不存在的应该当作silk格式。

**Comment by jarywong** [comment]
你的意思是这个xml是微信提供的，你只是根据这个xml去判断类型吗？
我以为你是根据文件头去判断的呢。

**Comment by BlueMatthew** [comment]
> 你的意思是这个xml是微信提供的，你只是根据这个xml去判断类型吗？ 我以为你是根据文件头去判断的呢。

我是这样猜的，我觉得微信应该有更明确的控制参数来做这个事情，而不是根据文件头。但是可能我的这个做法是不对的，文件头可能能更正确，汗

**Comment by BlueMatthew** [comment]
[v1.9.3.5.zip](https://github.com/BlueMatthew/WechatExporter/files/7959738/v1.9.3.5.zip)

没有更好的招了，就按非silk即amr的方式做了一下，有空帮忙试试看呢

**Comment by jarywong** [comment]
那个解决了，可是头像居然没了
```
07:48:54: Failed CP: ***\Portrait\***.jpg(not existed)  => ***\***_files\Portrait\***.jpg
```

**Comment by BlueMatthew** [comment]
新年前的好消息 头像估计是修改出来的bug 测试代码回退了估计能解决 我一会儿看一下


Best regards,
Matthew


在 2022年1月31日，07:06，jarywong ***@***.***> 写道：

﻿

那个解决了，可是头像居然没了

07:48:54: Failed CP: ***\Portrait\***.jpg(not existed)  => ***\***_files\Portrait\***.jpg


—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBlueMatthew%2FWechatExporter%2Fissues%2F65%23issuecomment-1025253793&data=04%7C01%7C%7C2bd0e650481c4bc8300a08d9e44518ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637791807705414689%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ovCqH9JvEZMnTl6A4iYlOgD%2BFFl67wJBo5dPYIg6OZw%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI6VD2FD46DCJ34C3FKDCBTUYW755ANCNFSM5LYSSMQA&data=04%7C01%7C%7C2bd0e650481c4bc8300a08d9e44518ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637791807705414689%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PaYQnAzp3QS%2F5wWTA6L52toJilh99%2F5TOSYi%2FMlQwPs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C2bd0e650481c4bc8300a08d9e44518ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637791807705414689%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XmM%2FrVdgkKAMxbhBO91Ui2i%2FUJybSPek8Vc%2FntR0nMo%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C2bd0e650481c4bc8300a08d9e44518ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637791807705414689%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ucMHnIsBBm4sba8al6pyUkyYDKCnGshwEFsLgfdEEcg%3D&reserved=0>.

**Comment by BlueMatthew** [comment]
> 那个解决了，可是头像居然没了
> 
> ```
> 07:48:54: Failed CP: ***\Portrait\***.jpg(not existed)  => ***\***_files\Portrait\***.jpg
> ```

突然想起来了，前面发的 那个版本，特地把下载禁用了，想着你测试会更快一点，发邮件前还想着要说这个，发的时候忘记写了。（掩面）

**Comment by BlueMatthew** [comment]
可以看看release里面的1.9.3.6 希望都没有问题了

**Comment by jarywong** [comment]
@BlueMatthew 嗯，目前看起来没问题了。
