### ISSUE TITLE
关于微信号？

### ISSUE THREAD

**Issue by jerryc127** [BlueMatthew/WechatExporter#67]
在 Portrait 找到了 微信号
为什么有些是原始的微信号 wxid
有些不是？
不能找到真实的么？

**Comment by BlueMatthew** [comment]
并不是所有的人都设置了微信号的 如果没有微信号 则输出路微信内部人士唯一的id

**Comment by jerryc127** [comment]
我看那个文件夹，连我本人，和我导出的那个人都是显示微信原始id，而不是微信号。。

**Comment by BlueMatthew** [comment]
> 我看那个文件夹，连我本人，和我导出的那个人都是显示微信原始id，而不是微信号。。

看到你说的是Portrait目录，这个目录下用的都是微信内部id，不是微信号。微信id，有些是wxid_开头的，也有一些是自己取的，可能和微信的用户的不同来源有关吧，

我前面提到的微信号，是导出的html中，每个消息数据中，会带一个wxid属性，这是微信号，微信号不存在，则用微信id

**Comment by BlueMatthew** [comment]
关闭本issue，如果还有问题，可以再提
