### ISSUE TITLE
请问通过iMazing把微信里面的documents文件夹拿出来之后要怎么导入到这个软件里

### ISSUE THREAD

**Issue by Planarians** [BlueMatthew/WechatExporter#68]
直接加入没反应提示解析iTunesBackup失败
因为用itunes备份量太大了c盘不够装不下用软连接备份又各种失败只能使用iMazing备份
可以自己伪装一个itunes备份的目录结构让他识别吗

**Comment by Planarians** [comment]
发现有个DecodedITunes的分支似乎是用来实现这个功能的 但是直接选择Documents文件夹也不行 是要怎么使用呢

**Comment by BlueMatthew** [comment]
Issue #27 里面有执行文件，不过那个比较早的时候做的，主分支又修复了很多bug，你可以先试试，回头我再更新一下分支。

**Comment by Planarians** [comment]
好的 谢谢 现在用的就是这个版本
但是每次导入document文件夹日志都显示LoginInfo2.dat not found
但我里面明明是有这个文件的 虽然用记事本打开是乱码

**Comment by BlueMatthew** [comment]
可能你的这个版本不一样，程序的判断不对了。能否把documents目录下的目录和文件列表截屏看一下呢

**Comment by Planarians** [comment]
![Inkedexplorer_JlpQP3qvV0_LI](https://user-images.githubusercontent.com/24474029/152509746-763ee0b0-b614-46a1-bc6b-39d12546cc6b.jpg)

**Comment by Planarians** [comment]
上面那个AppDomain-com.tencent.xin文件夹是我自己加的 想模拟iTunes备份的目录结构让正常版的软件识别 但是也识别不出来能识别出来itunes版本但是找不到wx数据_(:_」∠)_

**Comment by BlueMatthew** [comment]
你选择的目录是到 AppDomain-com.tencent.xin 这一级的吗？应该要选Documents上一级的目录。

**Comment by BlueMatthew** [comment]
你选择的目录是到 AppDomain-com.tencent.xin 这一级的吗？应该要选Documents上一级的目录。

**Comment by Planarians** [comment]
不是 分支软件里我直接选的documents了 
试了下用这个目录确实可以了 谢谢～

只导出了Documents 
里面还有shared library两个文件夹没导出 里面也会存储一些聊天数据吗

**Comment by BlueMatthew** [comment]
[v1.9.3.6-decodedbackup.zip](https://github.com/BlueMatthew/WechatExporter/files/8003505/v1.9.3.6-decodedbackup.zip)

我基于最新的代码编译了一个能解析itunes backup解码文件的程序，你也可以试试。

**Comment by BlueMatthew** [comment]
> shared library

shared library 目录下没有聊天记录，只是有一些头像文件。

**Comment by Planarians** [comment]
谢谢 新版本尝试了下也能正常使用 怪不得有些头像会显示不出来

**Comment by BlueMatthew** [comment]
我后面看看怎么把这个功能做成常规功能。先关闭当前issue。
