### ISSUE TITLE
消息记录问题

### ISSUE THREAD

**Issue by Gsmlvdeshui** [BlueMatthew/WechatExporter#73]
我自己删了一条信息然后用itunes备份出来以后
用另外一个软件可以扫描出来我刚才删除的信息
用我们这个软件读取不到刚才删除的信息
像这种删除的信息我们有办法读到吗?

**Comment by BlueMatthew** [comment]
目前没有特别去研究这一块，一种是通过sqlite的数据恢复（sqlite不会马上覆盖删除的数据的数据块），另外貌似微信的消息的文本表可能还存在这个消息，但是都没有仔细研究过。


________________________________
发件人: Gsmlvdeshui ***@***.***>
发送时间: 2022年2月24日 15:07
收件人: BlueMatthew/WechatExporter ***@***.***>
抄送: Subscribed ***@***.***>
主题: [BlueMatthew/WechatExporter] 消息记录问题 (Issue #73)


我自己删了一条信息然后用itunes备份出来以后
用另外一个软件可以扫描出来我刚才删除的信息
用我们这个软件读取不到刚才删除的信息
像这种删除的信息我们有办法读到吗?

―
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBlueMatthew%2FWechatExporter%2Fissues%2F73&data=04%7C01%7C%7C35fa0261cf3643872ff608d9f7644697%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637812832324663698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Pp9oLYbeqz62EZuputmVHMejY26z4nOC2W8Dk%2B5zIRw%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI6VD2HLZ7DHNVY27BCJEVTU4XKJ3ANCNFSM5PGQZ65Q&data=04%7C01%7C%7C35fa0261cf3643872ff608d9f7644697%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637812832324663698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hu8hYyQWvw2GTIb8U5OMEUcO8HEmd9x82bORZ9J49E4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C35fa0261cf3643872ff608d9f7644697%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637812832324663698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=piMzvr8%2F4d7Mp7krwm1ENIEWiz2BmoFXrjkZ%2BEmMEnc%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C35fa0261cf3643872ff608d9f7644697%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637812832324663698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XQy%2Ba7WgV5Zr8AYaIFIX9oSnbU1hNfXnnrwH1CMEfSM%3D&reserved=0>.

**Comment by Gsmlvdeshui** [comment]
好的,谢谢老哥
