### ISSUE TITLE
v1.9.3.6-x64-win，读取数据出现识别备注名称错误

### ISSUE THREAD

**Issue by crazy3min** [BlueMatthew/WechatExporter#76]
问题：读取iTunes备份的iphone数据，出现备注名称识别错误。

-------------------------------------------------日志-------------------------------------------------
07:08:31: [DBG] ITunes Database loaded.
07:08:31: iTunes版本：12.12.2.2, iOS版本：15.3, 微信版本：8.0.18，WechatExporter版本：v1.9.3.6-x64-win
07:08:31: [DBG] Length of field 1 in Documents/LoginInfo2.dat = 381
07:08:31: [DBG] Offset of field 1 in Documents/LoginInfo2.dat = 0/381
07:08:31: [DBG] UsrName from Documents/LoginInfo2.dat = wxid_sy0cmya4dit021
07:08:31: [DBG] DisplayName from Documents/LoginInfo2.dat = ***
07:08:31: [DBG] User from Documents/LoginInfo2.dat:wxid_sy0cmya4dit021(23ec891d12eb1891c3466999aec35e8f) => ***
07:08:31: [DBG] parseUserFromFolder starts...
07:08:31: [DBG] Find User Folder:23ec891d12eb1891c3466999aec35e8f
07:08:31: [DBG] mmsetting: Documents/MMappedKV/mmsetting.archive. => 2963c488d92fded1faefa54b9d5c88ddbe694fd2
07:08:31: [DBG] mmsetting: Documents/MMappedKV/mmsetting.archive.wxid_sy0cmya4dit021 => 42978d3a592afa60ffc3ad3898e4d0b2d60031f5
07:08:31: [DBG] Parse user:wxid_sy0cmya4dit021(23ec891d12eb1891c3466999aec35e8f) => ***
07:08:31: [DBG] Failed to parse mmsetting:wxid_sy0cmya4dit021
07:08:31: [DBG] Parse MMKV file: Documents/MMappedKV/mmsetting.archive.wxid_sy0cmya4dit021 => C:\Users\test\AppData\Roaming\Apple Computer\MobileSync\Backup\00008030-001845663652402E\42\42978d3a592afa60ffc3ad3898e4d0b2d60031f5
07:08:31: [DBG] Parse MMKV file: Documents/MMappedKV/mmsetting.archive.wxid_sy0cmya4dit021.crc => C:\Users\test\AppData\Roaming\Apple Computer\MobileSync\Backup\00008030-001845663652402E\1f\1fbd26e093bcff3368447f44943099ac0aa3d5cf
07:08:31: [DBG] MMKV lastActualSize from crc: 7405 crc file size:16384
07:08:31: [DBG] MMKV file size:16384
07:08:31: [DBG] Succeeded to parse mmkv:wxid_sy0cmya4dit021
07:08:31: [DBG] Wechat Users loaded.
07:08:32: [DBG] Wechat Friends(3382) for: *** loaded.

-------------------------------------------------截图-------------------------------------------------
<img width="636" alt="Snipaste_2022-03-05_08-41-46" src="https://user-images.githubusercontent.com/45255042/156860535-5a7a8a39-31f4-46fa-8740-05e5c6659b72.png">
<img width="632" alt="Snipaste_2022-03-05_08-45-06" src="https://user-images.githubusercontent.com/45255042/156860543-2604ee45-4207-4e83-810c-38da2867848b.png">
<img width="641" alt="Snipaste_2022-03-05_08-50-37" src="https://user-images.githubusercontent.com/45255042/156860561-5707376e-5573-4719-97d6-277dce9ccce1.png">

**Comment by BlueMatthew** [comment]
所以是有一个微信用户和ta的企业微信账号都是你的好友，并且名字都一样的情况下会出现串的情况，是这样吗？

**Comment by crazy3min** [comment]
1、企业微信用户的名称为“A”，但是名称被识别为“B”，“B”是我一个普通好友的备注名称。聊天记录内容是正常的，但对方的显示名称是错误的，为“B”

2、有个普通的群名称 “DD”，被识别成“E”，“E”是我一个普通好友的备注名称，并不在这个群里面。聊天记录内容是正常的，但群名称是错误的，为“E”。

**Comment by BlueMatthew** [comment]
我这边重现不出来，从代码层面没有看到什么特别的问题。移除了一段感觉不必要的处理显示名字的代码，然后每解析一个聊天群，就检查一下显示名是不是和已有的重复（当然有一些重复是存在的，正常的），可以从这些日志看有没有串名的线索。另外，列表增加了聊天群最后一条聊天记录，可能有助于区分。你有空可以试试。

[v1.9.4.0-x64-win-dbg.zip](https://github.com/BlueMatthew/WechatExporter/files/8310520/v1.9.4.0-x64-win-dbg.zip)

**Comment by crazy3min** [comment]
使用"v1.9.4.0-x64-win"读取，没有出现备注名称识别错误的问题。

**Comment by crazy3min** [comment]
1、十分抱歉，我之前备份的记录已经删除，现在使用iTunes重新备份后，使用“v1.9.4.0-x64-win-dbg2.zip ”无法复现“备注名称识别错误”的问题。

2、但是现在发现新的问题。
（1）“v1.9.4.0-x64-win-dbg” 出现无法正确识别公众号名称和群名称，“v1.9.4.0-x64-win-dbg2”识别正确。
![图片](https://user-images.githubusercontent.com/45255042/159402519-b967c9fa-15e9-4457-90e6-63a8d9f24395.png)

（2）“v1.9.4.0-x64-win-dbg2”不能识别企业微信联系人名称。
![图片](https://user-images.githubusercontent.com/45255042/159402839-8007c9c3-5ca9-4d7e-bc15-47b0e6e35c2d.png)


[v1.9.4.0-x64-win-dbg_日志.txt](https://github.com/BlueMatthew/WechatExporter/files/8320822/v1.9.4.0-x64-win-dbg_.txt)
[v1.9.4.0-x64-win-dbg2_日志 -.txt](https://github.com/BlueMatthew/WechatExporter/files/8320823/v1.9.4.0-x64-win-dbg2_.-.txt)

**Comment by BlueMatthew** [comment]
1.9.5调整过企业微信和群名的解析的方式，后面帮忙再关注一下是不是还有问题。

**Comment by crazy3min** [comment]
使用“ v1.9.5.5-x64-win.zip ”解析，没有出现错误。
