### ISSUE TITLE
感谢作者的mmkv解析实现

### ISSUE THREAD

**Issue by darkskygit** [BlueMatthew/WechatExporter#8]
我也开了个备份im的[坑](https://github.com/darkskygit/ChatImporter)，目标是让多种im备份到一个数据库里
新版的mmsetting我找了半天没找着，还好搜到了作者的代码，十分感谢 👍

**Comment by laris** [comment]
@darkskygit @BlueMatthew 

感谢维护了几年的项目，我最近研究了一下您的代码，并尝试用Rust代码解析数据。
在处理mmsetting.archive.${userid}的时候实在是看不懂，我这里这个文件看起来开头是32-bit 0，然后是0xFF_FF_FF_07，看起来也不是一个plist文件，所以我尝试解析plist失败，能不能请教一下代码里大概的逻辑原理？
```
Rust plist crate Value::from_reader()解析失败
Error { inner: ErrorImpl { kind: InvalidXmlUtf8, file_position: Some(FilePosition(497)) } }
```
