### ISSUE TITLE
文本输出格式不统一

### ISSUE THREAD

**Issue by erertertet** [BlueMatthew/WechatExporter#81]
如果信息是一个分享链接，输出格式是文本，那么信息附带的iso时间的括号就会谜之消失
版本1.9.4.0，iTunes版本：12.12.3.5, iOS版本：15.4, 微信版本：8.0.18.57，手机iPhone se 1

**Comment by BlueMatthew** [comment]
1.9.5.4应该解决了

**Comment by erertertet** [comment]
谢谢哥
