### ISSUE TITLE
按照时间倒序排列对话列表

### ISSUE THREAD

**Issue by MySadCaptain** [BlueMatthew/WechatExporter#82]
非常喜欢这款软件，比wxbackup的性能好很多，而且支持在NAS中保存的iPhone备份。

我在使用中有一个小问题，目前在选择要到导出的对话的时候，只能按照“名称”, “聊天记录数”和"微信账号“排序，没有办法像微信app里一样按照最后一条消息的时间倒序排列（最新聊天对话在最前面）。

如果能加上按照时间倒序排列对话的功能的话，每次导出就不用找半天聊天对象的名字了，会方便很多：）

**Comment by BlueMatthew** [comment]
默认就是按照最后一条消息的时间倒序排列的， :)

**Comment by MySadCaptain** [comment]
> 默认就是按照最后一条消息的时间倒序排列的， :)

好奇怪，我不知道我这里的对话排序混乱问题是只有我这里有，还是别人也会遇到。确实有一些最近的对话排在最上面，但是不是所有的对话都严格的按照时间倒序排列。

有一些天天聊天的对象（在微信app中排在首屏的）会排在列表的中间甚至末尾，需要翻很久才可以翻到。而有些很久没联系的人会排在很靠前的位置。

**Comment by BlueMatthew** [comment]
你用的是哪个版本 我核一下呢 昨晚我看了一下我自己的 顺序还是对的

**Comment by MySadCaptain** [comment]
> 你用的是哪个版本 我核一下呢 昨晚我看了一下我自己的 顺序还是对的

我之前用的是1.9.3，刚刚升级到了1.9.4试了下，排序没变。

不过得益于1.9.4显示最后一条消息的功能，我发现了可能的排序出错原因。有的很早之前的对话排在了前面，是因为WechatExporter中显示的最后一条消息和实际导出的后看到的最后一条消息不一致，WechatExporter中显示的最后一条消息在实际导出的聊天记录里根本没有（我也忘记是不是我手动在微信里删除了）。有的最近聊天却排在了后面，是因为“最后一条消息”那里显示为空，没有抓取到。

我猜测这种不一致可能是因为「WechatExporter中显示的最后一条消息」并不是从实际导出的记录里面选取的，而从别的什么来源，但是如果出现了类似删除了一部分对话记录的情况就会导致不一致：实际导出删了，但是最后一条消息的来源并没有删除。

还有的最后一条消息显示的是“-”，不明白是为什么。不过不靠谱的猜测，诸如表情、语音信息、通话、隐藏对话、免打扰等等有可能都会影响到基于最后一条信息的排序。

**Comment by BlueMatthew** [comment]
今天升级了手机上的微信重新试了一下，确实是有问题，新版本的一些数据存储方式改变过了，导致最后一条消息的获取一部分出现了错误。我调整一下。

**Comment by MySadCaptain** [comment]
> 今天升级了手机上的微信重新试了一下，确实是有问题，新版本的一些数据存储方式改变过了，导致最后一条消息的获取一部分出现了错误。我调整一下。

非常感谢！

**Comment by BlueMatthew** [comment]
可以看看1.9.5.4

**Comment by MySadCaptain** [comment]
> 可以看看1.9.5.4

感谢！我这里排序基本没问题了！ 不过有些对话的最后一条消息显示的是“-”，请问是怎么回事？

**Comment by BlueMatthew** [comment]
如果消息是非文本的，比如照片，视频，语音，或者分享链接的，不想在这个列表做复杂的解析，就直接显示个 "-"了 :)

**Comment by MySadCaptain** [comment]
> 如果消息是非文本的，比如照片，视频，语音，或者分享链接的，不想在这个列表做复杂的解析，就直接显示个 "-"了 :)

明白了，再次感谢！

**Comment by BlueMatthew** [comment]
这个issue我关了，有问题可以再提。
