### ISSUE TITLE
更改导出格式的UI/UX不明显

### ISSUE THREAD

**Issue by lingzhong** [BlueMatthew/WechatExporter#83]
第一次使用WechatExporter MacOS版本时，没找到怎样可以更改导出格式。

READ.md里有提到可以改，但我在MacOS版本的UI内没能找到就以为这只是Windows版本的功能。直到在Github Issues里面看到有用户在MacOS版本更改过导出格式才又回去应用UI找，才在MacOS menu bar找到。
![format_setting](https://user-images.githubusercontent.com/4011137/160138719-6bbeb46b-048a-476a-8840-02295fd9b975.png)

建议在应用UI内添加更改导出格式的UI元素，例如dropdown, radio buttons。

这个软件包很好用，谢谢！💯

**Comment by BlueMatthew** [comment]
主要是考虑到这些设置一般不会频繁改动，所以就放在菜单中，不占用主ui空间。后面我加一个新手引导说明一下 :)
