### ISSUE TITLE
无法增量导出，提示“输出目录下不存在前一次导出信息，增量导出失效”

### ISSUE THREAD

**Issue by tedwcy** [BlueMatthew/WechatExporter#85]
win11正式版（22000.593），iTunes（12.12.3.5），iOS 15.4，微信最新版。
操作流程：
1、使用iTunes本地无密码备份，然后用wechat exporter导出，均正常。
2、过几分钟，有微信新消息后，再次使用iTunes备份。
3、打开wechat exporter，没有改动输出目录，也没用动过目录下文件，导出时提示“输出目录下不存在前一次导出信息，增量导出失效”（增量备份选项一直打开着），并且根据备份时长来看，确实是全量备份。

另外有个疑问，如果不开增量备份，每次备份是否会把上次备份后手机上删除的东西在电脑上也同步删除？

**Comment by tedwcy** [comment]
测试了一下，增量导出不起作用的情况下，相当于重新备份，上次备份后手机上删除的东西在电脑上也会同步删除。
不知道是哪里出了问题导致无法增量备份？

**Comment by BlueMatthew** [comment]
应该是之前某一个版本改出bug了，晚上我会更新一个版本。

不过增量导出还是存在很多功能性的问题的，后面还需要好好想想。

**Comment by tedwcy** [comment]
> 应该是之前某一个版本改出bug了，晚上我会更新一个版本。
> 
> 不过增量导出还是存在很多功能性的问题的，后面还需要好好想想。

好的，那我晚上继续测试下新版本的“增量导出”功能。:+1:

**Comment by tedwcy** [comment]
刚刚试了一下1.9.5.6版本，增量导出功已正常，不会删除上次备份后微信中删除的内容

**Comment by BlueMatthew** [comment]
本issue先关闭了
