### ISSUE TITLE
1.9.5 版本崩溃问题

### ISSUE THREAD

**Issue by lxt20180608** [BlueMatthew/WechatExporter#88]
用了1.9.5.5和1.9.5.6，在选择保存为html格式时，第一个对话都没有导出完毕软件就直接卡死，没有任何响应，等待10分钟未果强行关闭；每次打开都是这样，只有选择txt时可以完成导出。
尝试更改输出目录，更改时软件直接卡死无响应，且程序管理器无法关闭。

**Comment by BlueMatthew** [comment]
是windows版本吗？每个对话中的进度条还在动吗？

**Comment by lxt20180608** [comment]
> 是windows版本吗？每个对话中的进度条还在动吗？

是Windows版本，对话中的进度条在刚开始没多久软件卡死之后就不会再动了

**Comment by BlueMatthew** [comment]
[wxexp_log.zip](https://github.com/BlueMatthew/WechatExporter/files/8513111/wxexp_log.zip)

我编译了一个带更多日志的版本，有空帮忙试试呢。如果程序卡住了，看看输出目录的日志，看看是否有新的日志产生。如果日志也不发生变化，看看最后的一部分日志有什么特别的信息。另外，如果卡在某一条消息的处理上，dbg子目录有lastmsg.txt中是最后一条处理的消息的内容，看看是否方便发出来（确认没有敏感内容）。

**Comment by lxt20180608** [comment]
好的，我可以试试，请问怎样发给我呢？邮箱是1355840069@qq.com

**Comment by BlueMatthew** [comment]
上面那个回复里面有链接，直接下载就可以了

**Comment by lxt20180608** [comment]
您好！您新编译的版本成功完全导出了我的所有聊天记录，设置与其他版本完全相同，唯一不同的是导出的速度明显比之前的版本慢一点，但是没有出现卡顿的现象。

**Comment by BlueMatthew** [comment]
> 

汗，那我出一个release版本，不知道是不是之前有什么bug被默默修掉了 ...

**Comment by BlueMatthew** [comment]
[v1.9.5.7-x64-win.zip](https://github.com/BlueMatthew/WechatExporter/files/8519809/v1.9.5.7-x64-win.zip)

有空再看看这个build正常伐

**Comment by lxt20180608** [comment]
好的，我测试一下

**Comment by lxt20180608** [comment]
可以正常导出全部内容，但一个小bug是，所有进度都完成之后，进度条由100%一直开始倒退，倒退到10%左右又开始增加，增加至70%多时软件自动关闭，显示导出的文件夹。由于软件自动关闭，我没有导出日志。

**Comment by BlueMatthew** [comment]
> 可以正常导出全部内容，但一个小bug是，所有进度都完成之后，进度条由100%一直开始倒退，倒退到10%左右又开始增加，增加至70%多时软件自动关闭，显示导出的文件夹。由于软件自动关闭，我没有导出日志。

进度条貌似是有点问题，一直懒得去改，汗

**Comment by lxt20180608** [comment]
正常完成了导出任务，没有自动关闭也没有闪退

**Comment by BlueMatthew** [comment]
那看来没有问题了，也不知道怎么修复了之前的闪退。先这样吧，后面有问题，可以再反馈。
