### ISSUE TITLE
希望能导出成一张张图片，或者一页一页的PDF

### ISSUE THREAD

**Issue by Seifon** [BlueMatthew/WechatExporter#9]
想把聊天记录打印成册，所以要是软件能够做到导出A4纸大小的PDF就完美了

**Comment by BlueMatthew** [comment]
chrome是可以直接把网页打印成pdf的，不知道你试过没有，不过不确定格式方面是不是有问题。不知道你试过没有，如果有问题，可以反馈给我

**Comment by Seifon** [comment]
> chrome是可以直接把网页打印成pdf的，不知道你试过没有，不过不确定格式方面是不是有问题。不知道你试过没有，如果有问题，可以反馈给我

但是太多页了，一页一页打印很麻烦的，希望大神能集成mdout：https://github.com/JabinGP/mdout   这款软件，支持命令行导出pdf

**Comment by BlueMatthew** [comment]
> > chrome是可以直接把网页打印成pdf的，不知道你试过没有，不过不确定格式方面是不是有问题。不知道你试过没有，如果有问题，可以反馈给我
> 
> 但是太多页了，一页一页打印很麻烦的，希望大神能集成mdout：https://github.com/JabinGP/mdout 这款软件，支持命令行导出pdf

chrome不是能把所有页都打印成pdf的吗？我唯一担心格式是不是不好

**Comment by BlueMatthew** [comment]
测试了一下，确实如果聊天记录比较多的话，打印成pdf非常慢。。

**Comment by BlueMatthew** [comment]
> > chrome是可以直接把网页打印成pdf的，不知道你试过没有，不过不确定格式方面是不是有问题。不知道你试过没有，如果有问题，可以反馈给我
> 
> 但是太多页了，一页一页打印很麻烦的，希望大神能集成mdout：https://github.com/JabinGP/mdout 这款软件，支持命令行导出pdf

最近在看怎么利用chrome，chrome也支持命令行的方式导出pdf
chrome --headless --disable-gpu --print-to-pdf="导出的pdf文件名" --print-to-pdf-no-header [html文件名]

MS Edge也是一样的命令，
msedge --headless --disable-gpu --print-to-pdf="导出的pdf文件名" --print-to-pdf-no-header [html文件名]

我已经在主分支集成了进来，不过还存在两个问题，一个是原有的进度不准确了，需要重新调整，第二个是转pdf还是比较慢的，看怎么改成多线程/进程处理。

你可以先尝试用这个命令行来转。

**Comment by BlueMatthew** [comment]
1.8.0程序输出了pdf转换的批量命令行，可以试试。

**Comment by BlueMatthew** [comment]
pdf已经实现，关闭issue
