### ISSUE TITLE
请问能否互换聊天者的位置？

### ISSUE THREAD

**Issue by wushu037** [BlueMatthew/WechatExporter#91]
女朋友的手机丢了，我想用我的账号导出我们俩的聊天记录

如果界面上能互换两个人的位置她看起来应该更方便些

(或者应该是可以指定显示在右侧的微信id？)

**Comment by BlueMatthew** [comment]
这么用心的男朋友，必须支持你。我看看怎么调一下。

**Comment by BlueMatthew** [comment]
[v1.9.5.8_x64_win_r.zip](https://github.com/BlueMatthew/WechatExporter/files/8609489/v1.9.5.8_x64_win_r.zip)

试试看这个程序，我只是粗略看了一下，左右互换了。

**Comment by wushu037** [comment]
十分感谢大佬！我试一下

**Comment by BlueMatthew** [comment]
> 十分感谢大佬！我试一下

可以吗？

**Comment by BlueMatthew** [comment]
先关闭issue，后续还有问题，可以再提issue
