### ISSUE TITLE
iTunes备份强制要求密码

### ISSUE THREAD

**Issue by daqingliu** [BlueMatthew/WechatExporter#96]
在用iTunes备份iPhone的时候，强制要求设置备份密码。
![ZMYO`XOLD25T@ STXPY Q)U](https://user-images.githubusercontent.com/17782148/169024800-979af4f8-1421-4b61-8f28-f285c5c1be69.png)

已经测试过：
1. 在mac上：同样要求设置密码；
2. 首先设置密码，再取消：取消时会失败。

请问这是iPhone哪儿需要设置吗？

感谢~

**Comment by BlueMatthew** [comment]
你看看你的iphone 设置中： 常规 > VPN 和设备管理里面，是不是有一些特殊的证书

**Comment by BlueMatthew** [comment]
你看看你的iphone 设置中： 常规 > VPN 和设备管理里面，是不是有一些特殊的证书
